$outputDir = "C:\obsidian\Main\Prog"

function Clean($s) { $s -replace '/','-' -replace '\*','' -replace ':','' -replace '\?','' -replace '"','' -replace '<','' -replace '>','' -replace '\|','' }

function New-Zettel($id, $title, $desc, $up, $side, $down) {
    $lines = @("$title", "")
    $lines += $desc
    if ($up.Count -gt 0) {
        $lines += ""
        foreach ($u in $up) { $lines += "→ [[$u]]" }
    }
    if ($side.Count -gt 0) {
        $lines += ""
        foreach ($s in $side) { $lines += "≈ [[$s]]" }
    }
    if ($down.Count -gt 0) {
        $lines += ""
        foreach ($d in $down) { $lines += "↓ [[$d]]" }
    }
    $lines += ""
    $lines += "---"
    $fn = "$(Clean($id)).md"
    [IO.File]::WriteAllText((Join-Path $outputDir $fn), ($lines -join "`r`n"), [Text.Encoding]::UTF8)
}

# ===== BACKEND - DATABASES =====
New-Zettel "INDEX PRIMARY KEY" "# INDEX, PRIMARY KEY #database #sql #уровень1" "Основной ключ таблицы, уникально идентифицирует строку." @("SQL Индексирование","Оптимизация запросов") @("UNIQUE Constraint","Foreign Key") @()
New-Zettel "B-TREE INDEX" "# B-TREE INDEX #database #indexing #уровень1" "Самобалансирующееся дерево поиска для быстрого доступа к данным." @("SQL Индексирование","Структуры данных") @("Hash Index","Bitmap Index") @("B+ Tree","B* Tree")
New-Zettel "NORMALIZATION 1NF" "# NORMALIZATION 1NF #database #design #уровень1" "Первая нормальная форма: атомарность данных в каждой ячейке." @("Нормализация БД","Database Design") @("Atomicity") @()
New-Zettel "ACID PROPERTIES" "# ACID PROPERTIES #database #transactions #уровень1" "Атомарность, Консистентность, Изоляция, Долговечность." @("Транзакции","Надежность БД") @("CAP Theorem") @("Atomicity","Consistency","Isolation","Durability")
New-Zettel "N+1 QUERY" "# N+1 QUERY #database #optimization #уровень1" "Проблема избыточных запросов при загрузке связанных данных." @("SQL Performance","ORM Optimization") @("Query Optimization") @("Eager Loading","Lazy Loading")
New-Zettel "SQL JOIN TYPES" "# SQL JOIN TYPES #database #sql #уровень1" "INNER, LEFT, RIGHT, FULL - способы объединения таблиц в SQL." @("SQL Fundamentals","Relational Model") @("Subqueries","Set Operations") @()
New-Zettel "TRANSACTION ISOLATION" "# TRANSACTION ISOLATION #database #transactions #уровень1" "Уровни изоляции транзакций от Read Uncommitted до Serializable." @("Транзакции","Concurrency Control") @("Pessimistic Locking","Optimistic Locking") @()
New-Zettel "DB REPLICATION" "# DB REPLICATION #database #scalability #уровень1" "Копирование данных на несколько узлов для отказоустойчивости." @("High Availability","Scalability") @("Sharding","Partitioning") @()
New-Zettel "DB SHARDING" "# DB SHARDING #database #scalability #уровень1" "Горизонтальное разделение таблиц по шардам для масштабирования." @("Scalability","Distributed Systems") @("Partitioning","DB Replication") @()
New-Zettel "FOREIGN KEY" "# FOREIGN KEY #database #sql #уровень1" "Ссылка на PRIMARY KEY другой таблицы для обеспечения целостности." @("Relational Model","Database Design") @("INDEX PRIMARY KEY","UNIQUE Constraint") @()
New-Zettel "SQL VIEW" "# SQL VIEW #database #sql #уровень1" "Виртуальная таблица на основе результата SELECT запроса." @("SQL Fundamentals","Database Design") @("Materialized View","CTE") @()
New-Zettel "STORED PROCEDURE" "# STORED PROCEDURE #database #sql #уровень1" "Набор SQL-инструкций, хранимый на сервере БД." @("SQL Fundamentals","Backend Development") @("Function","Trigger") @()
New-Zettel "DB INDEX" "# DB INDEX #database #performance #уровень1" "Структура данных для ускорения поиска и сортировки записей." @("SQL Performance","Database Design") @("B-TREE INDEX","Hash Index") @()
New-Zettel "SQL SUBQUERY" "# SQL SUBQUERY #database #sql #уровень1" "Вложенный SELECT запрос внутри основного SQL запроса." @("SQL Fundamentals","Query Optimization") @("CTE","SQL JOIN TYPES") @()
New-Zettel "CTE" "# CTE #database #sql #уровень1" "Common Table Expression - временный именованный набор результатов." @("SQL Fundamentals","Query Optimization") @("SQL SUBQUERY","SQL VIEW") @()
New-Zettel "CAP THEOREM" "# CAP THEOREM #database #distributed #уровень1" "Consistency, Availability, Partition Tolerance - выбрать два." @("Distributed Systems","Database Design") @("ACID PROPERTIES","BASE") @()
New-Zettel "BASE PROPERTIES" "# BASE PROPERTIES #database #nosql #уровень1" "Basically Available, Soft state, Eventual consistency для NoSQL." @("NoSQL","Distributed Systems") @("CAP THEOREM","ACID PROPERTIES") @()
New-Zettel "NOSQL DOCUMENT" "# NOSQL DOCUMENT #database #nosql #уровень1" "Хранение данных в формате JSON и BSON документов без схемы." @("NoSQL","Database Design") @("Key-Value Store","Column Family") @()
New-Zettel "NOSQL KEY-VALUE" "# NOSQL KEY-VALUE #database #nosql #уровень1" "Простейшая модель данных: ключ указывает на значение." @("NoSQL","Caching") @("NOSQL DOCUMENT","Column Family") @()
New-Zettel "DB LOCKING" "# DB LOCKING #database #concurrency #уровень1" "Механизмы блокировки строк и таблиц для конкурентного доступа." @("Concurrency Control","TRANSACTION ISOLATION") @("Optimistic Locking","Pessimistic Locking") @()
New-Zettel "SQL GROUP BY" "# SQL GROUP BY #database #sql #уровень1" "Агрегация строк по группам с функциями COUNT, SUM, AVG." @("SQL Fundamentals","Analytics") @("SQL JOIN TYPES","SQL WINDOW FUNCTION") @()
New-Zettel "SQL WINDOW FUNCTION" "# SQL WINDOW FUNCTION #database #sql #аналитика #уровень1" "Функции OVER и PARTITION BY для аналитических оконных вычислений." @("SQL Fundamentals","Analytics") @("SQL GROUP BY","CTE") @()
New-Zettel "MATERIALIZED VIEW" "# MATERIALIZED VIEW #database #performance #уровень1" "Физически сохраненный результат запроса для быстрого доступа." @("Database Design","Performance Optimization") @("SQL VIEW","DB INDEX") @()
New-Zettel "DEADLOCK" "# DEADLOCK #database #concurrency #уровень1" "Взаимная блокировка транзакций, ожидающих ресурсы друг друга." @("Concurrency Control","DB LOCKING") @("TRANSACTION ISOLATION") @()

# ===== BACKEND - API =====
New-Zettel "REST ENDPOINT" "# REST ENDPOINT #api #http #backend #уровень1" "Принципы дизайна RESTful API endpoints с правильными HTTP методами." @("REST Architecture","API Design") @("GraphQL Schema","SOAP") @()
New-Zettel "JWT AUTH" "# JWT AUTH #security #auth #tokens #уровень1" "JSON Web Token для безопасной аутентификации и авторизации." @("Authentication Methods","Security Best Practices") @("OAuth 2.0","Session Cookies") @()
New-Zettel "CORS" "# CORS #http #security #api #уровень1" "Cross-Origin Resource Sharing - управление кросс-доменными запросами." @("HTTP Headers","Browser Security") @("Same-Origin Policy","CSP Header") @()
New-Zettel "CACHING STRATEGY" "# CACHING STRATEGY #performance #optimization #уровень1" "Стратегии кэширования для снижения нагрузки на БД и серверы." @("Performance Optimization","Distributed Systems") @("CDN","Redis Cache") @()
New-Zettel "GRAPHQL SCHEMA" "# GRAPHQL SCHEMA #api #graphql #backend #уровень1" "Типизированная схема данных для GraphQL API с типами и связями." @("GraphQL","API Design") @("REST ENDPOINT","SOAP") @()
New-Zettel "RATE LIMITING" "# RATE LIMITING #api #security #performance #уровень1" "Ограничение числа запросов к API за единицу времени." @("API Security","Performance") @("Throttling","Backpressure") @()
New-Zettel "API VERSIONING" "# API VERSIONING #api #rest #backend #уровень1" "Стратегии управления версиями: URL, Header, Query parameter." @("REST Architecture","API Design") @("GRAPHQL SCHEMA") @()
New-Zettel "API GATEWAY" "# API GATEWAY #api #architecture #microservices #уровень1" "Единая точка входа для маршрутизации и аутентификации запросов." @("Microservices","API Architecture") @("Reverse Proxy","Load Balancer") @()
New-Zettel "WEBSOCKET" "# WEBSOCKET #api #realtime #protocol #уровень1" "Протокол двусторонней связи в реальном времени поверх TCP." @("Real-time","Web Protocols") @("HTTP Long Polling","SSE") @()
New-Zettel "HTTP METHODS" "# HTTP METHODS #http #protocol #web #уровень1" "GET, POST, PUT, DELETE, PATCH - стандартные HTTP методы." @("HTTP Protocol","REST Architecture") @("HTTP Status Codes") @()
New-Zettel "HTTP STATUS CODES" "# HTTP STATUS CODES #http #protocol #web #уровень1" "Коды 2xx успех, 3xx редирект, 4xx ошибка клиента, 5xx ошибка сервера." @("HTTP Protocol","API Development") @("HTTP METHODS") @()
New-Zettel "OAUTH 2.0" "# OAUTH 2.0 #security #auth #protocol #уровень1" "Фреймворк авторизации с делегированием доступа через токены." @("Authentication","Security") @("JWT AUTH","SAML") @()
New-Zettel "MESSAGE QUEUE" "# MESSAGE QUEUE #architecture #async #distributed #уровень1" "Промежуточный слой для асинхронной коммуникации между сервисами." @("Async Architecture","Distributed Systems") @("Pub-Sub","Event Bus") @()
New-Zettel "EVENT DRIVEN" "# EVENT DRIVEN #architecture #reactive #уровень1" "Архитектура, реагирующая на события вместо прямых вызовов." @("Software Architecture","Async Patterns") @("MESSAGE QUEUE","CQRS") @()
New-Zettel "RPC PROTOCOL" "# RPC PROTOCOL #api #protocol #backend #уровень1" "Remote Procedure Call - вызов функций на удаленном сервере." @("API Patterns","Distributed Systems") @("REST ENDPOINT","GRAPHQL SCHEMA") @()
New-Zettel "SWAGGER OPENAPI" "# SWAGGER OPENAPI #api #documentation #tools #уровень1" "Спецификация OpenAPI для документирования RESTful API." @("API Development","Documentation") @("GRAPHQL SCHEMA","REST ENDPOINT") @()
New-Zettel "HATEOAS" "# HATEOAS #api #rest #hypermedia #уровень1" "Hypermedia as Engine of Application State - ссылки в ответах API." @("REST Architecture","API Design") @("REST ENDPOINT","SWAGGER OPENAPI") @()
New-Zettel "BACKPRESSURE" "# BACKPRESSURE #api #async #resilience #уровень1" "Механизм контроля нагрузки, когда потребитель не успевает за производителем." @("Resilience","Async Systems") @("RATE LIMITING","MESSAGE QUEUE") @()

# ===== BACKEND - DESIGN PATTERNS =====
New-Zettel "SINGLETON" "# SINGLETON #design-patterns #creational #уровень1" "Паттерн для создания единственного экземпляра класса." @("Design Patterns","Creational") @("FACTORY METHOD") @()
New-Zettel "OBSERVER" "# OBSERVER #design-patterns #behavioral #уровень1" "Паттерн оповещения множества объектов об изменениях." @("Design Patterns","Behavioral") @("Pub-Sub","EVENT DRIVEN") @()
New-Zettel "STRATEGY" "# STRATEGY #design-patterns #behavioral #уровень1" "Инкапсуляция семейства алгоритмов для взаимной замены." @("Design Patterns","Behavioral") @("STATE PATTERN","COMMAND PATTERN") @()
New-Zettel "FACTORY METHOD" "# FACTORY METHOD #design-patterns #creational #уровень1" "Создание объектов через фабричный метод в подклассах." @("Design Patterns","Creational") @("BUILDER PATTERN","SINGLETON") @()
New-Zettel "DI CONTAINER" "# DI CONTAINER #design-patterns #architecture #уровень1" "Внедрение зависимостей через конструктор или сеттер." @("Design Patterns","SOLID") @("IoC Container","Service Locator") @()
New-Zettel "ADAPTER" "# ADAPTER #design-patterns #structural #уровень1" "Позволяет объектам с несовместимыми интерфейсами работать вместе." @("Design Patterns","Structural") @("FACADE","BRIDGE PATTERN") @()
New-Zettel "DECORATOR" "# DECORATOR #design-patterns #structural #уровень1" "Динамическое добавление функциональности объекту без изменения класса." @("Design Patterns","Structural") @("ADAPTER","PROXY PATTERN") @()
New-Zettel "PROXY PATTERN" "# PROXY PATTERN #design-patterns #structural #уровень1" "Заместитель для контроля доступа или отложенной загрузки объекта." @("Design Patterns","Structural") @("DECORATOR","ADAPTER") @()
New-Zettel "BUILDER PATTERN" "# BUILDER PATTERN #design-patterns #creational #уровень1" "Пошаговое создание сложных объектов с разделением конфигурации." @("Design Patterns","Creational") @("FACTORY METHOD","PROTOTYPE") @()
New-Zettel "COMMAND PATTERN" "# COMMAND PATTERN #design-patterns #behavioral #уровень1" "Инкапсуляция запроса как объекта с отменой операций." @("Design Patterns","Behavioral") @("OBSERVER","STRATEGY") @()
New-Zettel "ITERATOR" "# ITERATOR #design-patterns #behavioral #уровень1" "Последовательный доступ к элементам коллекции без раскрытия структуры." @("Design Patterns","Behavioral") @("COMPOSITE","OBSERVER") @()
New-Zettel "COMPOSITE" "# COMPOSITE #design-patterns #structural #уровень1" "Группировка объектов в древовидные структуры для единого интерфейса." @("Design Patterns","Structural") @("DECORATOR","ITERATOR") @()
New-Zettel "FACADE" "# FACADE #design-patterns #structural #уровень1" "Упрощенный интерфейс к сложной системе классов." @("Design Patterns","Structural") @("ADAPTER","PROXY PATTERN") @()
New-Zettel "STATE PATTERN" "# STATE PATTERN #design-patterns #behavioral #уровень1" "Изменение поведения объекта при изменении внутреннего состояния." @("Design Patterns","Behavioral") @("STRATEGY","COMMAND PATTERN") @()
New-Zettel "TEMPLATE METHOD" "# TEMPLATE METHOD #design-patterns #behavioral #уровень1" "Скелет алгоритма с делегированием шагов подклассам." @("Design Patterns","Behavioral") @("STRATEGY","FACTORY METHOD") @()
New-Zettel "PROTOTYPE" "# PROTOTYPE #design-patterns #creational #уровень1" "Клонирование объектов через прототип вместо создания с нуля." @("Design Patterns","Creational") @("FACTORY METHOD","BUILDER PATTERN") @()
New-Zettel "FLYWEIGHT" "# FLYWEIGHT #design-patterns #structural #memory #уровень1" "Разделение общего состояния между множеством объектов для экономии памяти." @("Design Patterns","Structural") @("SINGLETON","COMPOSITE") @()
New-Zettel "CHAIN OF RESPONSIBILITY" "# CHAIN OF RESPONSIBILITY #design-patterns #behavioral #уровень1" "Передача запроса по цепочке обработчиков до первого подходящего." @("Design Patterns","Behavioral") @("COMMAND PATTERN","OBSERVER") @()
New-Zettel "MEDIATOR" "# MEDIATOR #design-patterns #behavioral #уровень1" "Централизация коммуникации между объектами через посредника." @("Design Patterns","Behavioral") @("OBSERVER","FACADE") @()
New-Zettel "MEMENTO" "# MEMENTO #design-patterns #behavioral #уровень1" "Сохранение и восстановление внутреннего состояния объекта." @("Design Patterns","Behavioral") @("COMMAND PATTERN","STATE PATTERN") @()

# ===== FRONTEND - REACT =====
New-Zettel "VIRTUAL DOM" "# VIRTUAL DOM #react #frontend #optimization #уровень1" "Виртуальное представление DOM для оптимизации обновлений." @("React Architecture","Performance") @("Fiber","Shadow DOM") @()
New-Zettel "REACT HOOKS" "# REACT HOOKS #react #state-management #уровень1" "useState, useEffect и другие hooks для управления состоянием и side effects." @("React Hooks","State Management") @("Class Components") @()
New-Zettel "COMPONENT LIFECYCLE" "# COMPONENT LIFECYCLE #react #frontend #уровень1" "Стадии жизни компонента: монтирование, обновление, размонтирование." @("React Fundamentals","Component Architecture") @("REACT HOOKS","Fiber") @()
New-Zettel "PROP DRILLING" "# PROP DRILLING #react #antipattern #уровень1" "Проблема передачи props через множество уровней компонентов." @("React Patterns","State Management") @("REACT CONTEXT","Redux") @()
New-Zettel "REACT CONTEXT" "# REACT CONTEXT #react #state-management #уровень1" "Механизм передачи данных через дерево компонентов без props." @("React Hooks","State Management") @("PROP DRILLING","Redux") @()
New-Zettel "REACT KEY" "# REACT KEY #react #rendering #performance #уровень1" "Уникальный key для идентификации элементов при повторном рендеринге." @("React Fundamentals","Performance") @("VIRTUAL DOM","COMPONENT LIFECYCLE") @()
New-Zettel "REACT REFS" "# REACT REFS #react #dom #hooks #уровень1" "useRef для доступа к DOM-элементам и хранения мутируемых значений." @("React Hooks","DOM") @("REACT HOOKS") @()
New-Zettel "REACT PORTAL" "# REACT PORTAL #react #dom #ui #уровень1" "Рендеринг дочерних элементов в DOM-узел вне родительской иерархии." @("React Patterns","DOM") @("REACT REFS","Portal Pattern") @()
New-Zettel "JSX" "# JSX #react #syntax #javascript #уровень1" "Расширение JavaScript для описания UI в React компонентах." @("React Fundamentals","JavaScript") @("Template Literals","Hyperscript") @()
New-Zettel "REACT MEMO" "# REACT MEMO #react #optimization #performance #уровень1" "Мемоизация компонента для предотвращения лишних ререндеров." @("React Optimization","Performance") @("useMemo","useCallback") @()
New-Zettel "REACT REDUX" "# REACT REDUX #react #state-management #redux #уровень1" "Глобальное хранилище состояния с иммутабельными обновлениями через reducers." @("State Management","Redux") @("REACT CONTEXT","REACT HOOKS") @()
New-Zettel "REACT ROUTER" "# REACT ROUTER #react #routing #spa #уровень1" "Клиентская маршрутизация для Single Page Applications на React." @("React Ecosystem","SPA") @("Next.js","Gatsby") @()
New-Zettel "REACT FORMS" "# REACT FORMS #react #forms #ux #уровень1" "Управление формами: controlled vs uncontrolled компоненты." @("React Patterns","Forms") @("REACT HOOKS","REACT REFS") @()
New-Zettel "REACT TESTING" "# REACT TESTING #react #testing #quality #уровень1" "Тестирование React компонентов с React Testing Library." @("Testing","React") @("UNIT TESTING","E2E TESTING") @()
New-Zettel "REACT SERVER COMPONENTS" "# REACT SERVER COMPONENTS #react #architecture #rendering #уровень1" "Компоненты, рендерящиеся на сервере без клиентского JS." @("React Architecture","Rendering") @("Next.js","SSR") @()

# ===== DEVOPS =====
New-Zettel "DOCKER CONTAINER" "# DOCKER CONTAINER #devops #containerization #уровень1" "Контейнеризация приложения с Docker для портативности." @("Containerization","DevOps Tools") @("Kubernetes Pod","Virtual Machine") @()
New-Zettel "KUBECTL" "# KUBECTL #kubernetes #devops #cli #уровень1" "CLI для управления Kubernetes кластером." @("Kubernetes","Orchestration") @("Docker Swarm","Helm") @()
New-Zettel "CI/CD PIPELINE" "# CI/CD PIPELINE #devops #automation #уровень1" "Непрерывная интеграция и развертывание для автоматизации релизов." @("DevOps Practices","Automation") @("GitHub Actions","Jenkins") @()
New-Zettel "LOAD BALANCING" "# LOAD BALANCING #devops #scalability #networking #уровень1" "Распределение нагрузки между серверами для масштабируемости." @("Scalability","Distributed Systems") @("Reverse Proxy","Round Robin") @()
New-Zettel "DOCKER COMPOSE" "# DOCKER COMPOSE #devops #docker #orchestration #уровень1" "Инструмент для запуска многоконтейнерных Docker приложений." @("Containerization","DevOps") @("DOCKER CONTAINER","KUBECTL") @()
New-Zettel "DOCKERFILE" "# DOCKERFILE #devops #docker #build #уровень1" "Текстовый файл с инструкциями для сборки Docker образа." @("Containerization","Build") @("DOCKER CONTAINER","DOCKER COMPOSE") @()
New-Zettel "TERRAFORM" "# TERRAFORM #devops #iac #automation #уровень1" "Infrastructure as Code: управление инфраструктурой через конфиги." @("IaC","DevOps Tools") @("Ansible","CloudFormation") @()
New-Zettel "ANSIBLE" "# ANSIBLE #devops #automation #config #уровень1" "Декларативная автоматизация конфигурации серверов." @("Configuration Management","DevOps") @("TERRAFORM","Chef") @()
New-Zettel "KUBERNETES POD" "# KUBERNETES POD #kubernetes #container #уровень1" "Минимальная единица развертывания в Kubernetes с одним или несколькими контейнерами." @("Kubernetes","Orchestration") @("DOCKER CONTAINER","KUBERNETES SERVICE") @()
New-Zettel "KUBERNETES SERVICE" "# KUBERNETES SERVICE #kubernetes #networking #уровень1" "Абстракция сетевого доступа к группе Pod'ов." @("Kubernetes","Networking") @("KUBERNETES POD","KUBERNETES INGRESS") @()
New-Zettel "KUBERNETES INGRESS" "# KUBERNETES INGRESS #kubernetes #networking #http #уровень1" "Управление внешним HTTP/HTTPS доступом к сервисам кластера." @("Kubernetes","Networking") @("KUBERNETES SERVICE","Load Balancer") @()
New-Zettel "HELM" "# HELM #kubernetes #package #devops #уровень1" "Пакетный менеджер для Kubernetes приложений." @("Kubernetes","DevOps") @("KUBECTL","Kustomize") @()
New-Zettel "PROMETHEUS" "# PROMETHEUS #devops #monitoring #metrics #уровень1" "Система мониторинга и сбора метрик с временными рядами." @("Observability","Monitoring") @("Grafana","Alertmanager") @()
New-Zettel "GRAFANA" "# GRAFANA #devops #visualization #monitoring #уровень1" "Платформа для визуализации метрик и создания дашбордов." @("Observability","Visualization") @("PROMETHEUS","Kibana") @()
New-Zettel "ELASTIC STACK" "# ELASTIC STACK #devops #logging #search #уровень1" "Elasticsearch, Logstash, Kibana для сбора и анализа логов." @("Logging","Observability") @("PROMETHEUS","GRAFANA") @()
New-Zettel "JENKINS" "# JENKINS #devops #automation #ci #уровень1" "Сервер автоматизации для CI/CD с поддержкой пайплайнов." @("CI/CD","Automation") @("GitHub Actions","GitLab CI") @()
New-Zettel "GITHUB ACTIONS" "# GITHUB ACTIONS #devops #ci #automation #уровень1" "Платформа CI/CD встроенная в GitHub для автоматизации workflows." @("CI/CD","GitHub") @("JENKINS","GitLab CI") @()
New-Zettel "SITE RELIABILITY" "# SITE RELIABILITY #devops #sre #reliability #уровень1" "Применение инженерных практик к эксплуатации систем." @("Reliability","DevOps") @("OBSERVABILITY","SLI SLO") @()
New-Zettel "SLI SLO SLA" "# SLI SLO SLA #devops #reliability #metrics #уровень1" "Индикаторы и цели уровня обслуживания для надежности систем." @("Reliability","SRE") @("PROMETHEUS","GRAFANA") @()

# ===== ALGORITHMS =====
New-Zettel "BIG O" "# BIG O #algorithms #complexity #notation #уровень1" "Математическая нотация для асимптотической сложности алгоритмов." @("Algorithm Analysis","Mathematics") @("TIME COMPLEXITY","SPACE COMPLEXITY") @()
New-Zettel "BINARY SEARCH" "# BINARY SEARCH #algorithms #search #log #уровень1" "Поиск элемента в отсортированном массиве за O(log n)." @("Search Algorithms","Divide and Conquer") @("LINEAR SEARCH","JUMP SEARCH") @()
New-Zettel "QUICKSORT" "# QUICKSORT #algorithms #sorting #divide #уровень1" "Быстрая сортировка с средней сложностью O(n log n)." @("Sorting Algorithms","Divide and Conquer") @("MERGESORT","HEAPSORT") @()
New-Zettel "TIME COMPLEXITY" "# TIME COMPLEXITY #algorithms #complexity #analysis #уровень1" "Оценка времени выполнения алгоритма в зависимости от размера входа." @("Algorithm Analysis","BIG O") @("SPACE COMPLEXITY") @()
New-Zettel "SPACE COMPLEXITY" "# SPACE COMPLEXITY #algorithms #complexity #memory #уровень1" "Оценка объема памяти, необходимой алгоритму для выполнения." @("Algorithm Analysis","BIG O") @("TIME COMPLEXITY") @()
New-Zettel "HASH TABLE" "# HASH TABLE #algorithms #data-structure #map #уровень1" "Структура ключ-значение с доступом O(1) через хеш-функцию." @("Data Structures","Algorithms") @("Dictionary","Map") @()
New-Zettel "LINKED LIST" "# LINKED LIST #algorithms #data-structure #sequential #уровень1" "Последовательность узлов с указателями на следующий элемент." @("Data Structures","Algorithms") @("ARRAY","STACK") @()
New-Zettel "STACK DS" "# STACK DS #algorithms #data-structure #lifo #уровень1" "Структура LIFO: последним пришел, первым вышел." @("Data Structures","Algorithms") @("QUEUE DS","LINKED LIST") @()
New-Zettel "QUEUE DS" "# QUEUE DS #algorithms #data-structure #fifo #уровень1" "Структура FIFO: первым пришел, первым вышел." @("Data Structures","Algorithms") @("STACK DS","DEQUE") @()
New-Zettel "RECURSION" "# RECURSION #algorithms #programming #divide #уровень1" "Функция, вызывающая саму себя, для решения подзадач." @("Algorithms","Programming") @("Iteration","Divide and Conquer") @()
New-Zettel "DYNAMIC PROGRAMMING" "# DYNAMIC PROGRAMMING #algorithms #optimization #dp #уровень1" "Решение через перекрывающиеся подзадачи с мемоизацией." @("Algorithm Design","Optimization") @("GREEDY","DIVIDE AND CONQUER") @()
New-Zettel "GREEDY" "# GREEDY #algorithms #optimization #choice #уровень1" "Локально оптимальный выбор на каждом шагу для глобального результата." @("Algorithm Design","Optimization") @("DYNAMIC PROGRAMMING","RECURSION") @()
New-Zettel "BFS DFS" "# BFS DFS #algorithms #graph #search #уровень1" "BFS для кратчайшего пути, DFS для поиска в глубину." @("Graph Algorithms","Search") @("BINARY SEARCH","TREE TRAVERSAL") @()
New-Zettel "TREE TRAVERSAL" "# TREE TRAVERSAL #algorithms #tree #recursion #уровень1" "Pre-order, In-order, Post-order обходы бинарного дерева." @("Tree Algorithms","Data Structures") @("BFS DFS","RECURSION") @()
New-Zettel "MERGESORT" "# MERGESORT #algorithms #sorting #divide #уровень1" "Сортировка слиянием за O(n log n) с устойчивым порядком." @("Sorting","Divide and Conquer") @("QUICKSORT","HEAPSORT") @()
New-Zettel "HEAPSORT" "# HEAPSORT #algorithms #sorting #heap #уровень1" "Сортировка на основе кучи за O(n log n) без дополнительной памяти." @("Sorting","Heap") @("QUICKSORT","MERGESORT") @()
New-Zettel "DIJKSTRA" "# DIJKSTRA #algorithms #graph #shortest-path #уровень1" "Поиск кратчайшего пути во взвешенном графе с неотрицательными ребрами." @("Graph Algorithms","Shortest Path") @("BFS DFS","A* SEARCH") @()
New-Zettel "A* SEARCH" "# A* SEARCH #algorithms #graph #heuristic #уровень1" "Эвристический поиск кратчайшего пути с эвристикой." @("Graph Algorithms","Pathfinding") @("DIJKSTRA","BFS DFS") @()
New-Zettel "TWO POINTERS" "# TWO POINTERS #algorithms #two-pointer #array #уровень1" "Техника двух указателей для обхода массива с разных сторон." @("Algorithm Techniques","Array") @("SLIDING WINDOW","BINARY SEARCH") @()
New-Zettel "SLIDING WINDOW" "# SLIDING WINDOW #algorithms #array #subarray #уровень1" "Техника скользящего окна для подмассивов и подстрок." @("Algorithm Techniques","Array") @("TWO POINTERS","DYNAMIC PROGRAMMING") @()

# ===== FRONTEND - CSS =====
New-Zettel "CSS FLEXBOX" "# CSS FLEXBOX #css #layout #frontend #уровень1" "Одномерная система компоновки элементов в CSS." @("CSS Layout","Frontend") @("CSS GRID","Float") @()
New-Zettel "CSS GRID" "# CSS GRID #css #layout #grid #уровень1" "Двумерная система сеток для сложных макетов." @("CSS Layout","Frontend") @("CSS FLEXBOX") @()
New-Zettel "CSS ANIMATION" "# CSS ANIMATION #css #motion #ui #уровень1" "Анимация элементов через transitions и keyframes." @("CSS","Frontend") @("JavaScript Animation","Canvas API") @()
New-Zettel "CSS RESPONSIVE" "# CSS RESPONSIVE #css #responsive #mobile #уровень1" "Адаптивный дизайн через media queries и относительные единицы." @("CSS Layout","Responsive Design") @("CSS FLEXBOX","CSS GRID") @()
New-Zettel "CSS SPECIFICITY" "# CSS SPECIFICITY #css #selectors #cascade #уровень1" "Правила приоритета CSS селекторов при конфликте стилей." @("CSS Fundamentals","Selectors") @("CSS Inheritance","Cascade") @()
New-Zettel "CSS CUSTOM PROPS" "# CSS CUSTOM PROPS #css #variables #design-systems #уровень1" "CSS переменные для переиспользования значений в стилях." @("CSS Fundamentals","Design Systems") @("SCSS Variables","Preprocessors") @()
New-Zettel "HTML SEMANTIC" "# HTML SEMANTIC #html #accessibility #semantics #уровень1" "Семантические теги HTML5 для структуры и доступности." @("HTML5","Accessibility") @("ARIA","HTML Elements") @()
New-Zettel "HTML FORMS" "# HTML FORMS #html #forms #ux #уровень1" "Элементы и атрибуты для создания веб-форм." @("HTML5","Frontend") @("REACT FORMS","Form Validation") @()
New-Zettel "CSS PSEUDO-CLASSES" "# CSS PSEUDO-CLASSES #css #selectors #states #уровень1" "Селекторы :hover, :focus, :nth-child для особых состояний." @("CSS Fundamentals","Selectors") @("CSS PSEUDO-ELEMENTS","CSS SPECIFICITY") @()
New-Zettel "CSS PSEUDO-ELEMENTS" "# CSS PSEUDO-ELEMENTS #css #selectors #content #уровень1" "::before и ::after для вставки контента до и после элемента." @("CSS Fundamentals","Selectors") @("CSS PSEUDO-CLASSES") @()
New-Zettel "CSS BOX MODEL" "# CSS BOX MODEL #css #fundamentals #layout #уровень1" "Content, Padding, Border, Margin - основа расчета размеров." @("CSS Fundamentals","Layout") @("CSS SPECIFICITY") @()
New-Zettel "CSS POSITIONING" "# CSS POSITIONING #css #layout #position #уровень1" "Static, Relative, Absolute, Fixed, Sticky - типы позиционирования." @("CSS Layout","Positioning") @("CSS FLEXBOX","CSS BOX MODEL") @()
New-Zettel "CANVAS API" "# CANVAS API #html #graphics #javascript #уровень1" "Элемент canvas для рисования 2D графики через JavaScript." @("HTML5","Graphics") @("SVG","WebGL") @()
New-Zettel "CSS TRANSITIONS" "# CSS TRANSITIONS #css #animation #interaction #уровень1" "Плавные изменения CSS свойств между состояниями." @("CSS Animation","UX") @("CSS ANIMATION","CSS CUSTOM PROPS") @()
New-Zettel "CSS PREPROCESSORS" "# CSS PREPROCESSORS #css #scss #less #tools #уровень1" "SASS, SCSS, LESS - расширения CSS с переменными и миксинами." @("CSS","Tools") @("CSS CUSTOM PROPS") @()
New-Zettel "CSS TAILWIND" "# CSS TAILWIND #css #utility #framework #уровень1" "Utility-first CSS фреймворк с классами-утилитами." @("CSS","Framework") @("CSS PREPROCESSORS","CSS CUSTOM PROPS") @()
New-Zettel "CSS BEM" "# CSS BEM #css #methodology #naming #уровень1" "Block Element Modifier - методология именования CSS классов." @("CSS","Methodology") @("CSS SPECIFICITY") @()
New-Zettel "CSS CONTAINER QUERIES" "# CSS CONTAINER QUERIES #css #responsive #container #уровень1" "Адаптация стилей на основе размера контейнера, не viewport." @("CSS Layout","Responsive") @("CSS RESPONSIVE","CSS GRID") @()

# ===== LANGUAGES =====
New-Zettel "JS CLOSURES" "# JS CLOSURES #javascript #functions #scope #уровень1" "Функция, запоминающая свою лексическую область видимости." @("JavaScript","Functional") @("JS SCOPE","JS HOISTING") @()
New-Zettel "JS PROMISE" "# JS PROMISE #javascript #async #promise #уровень1" "Объект для работы с асинхронными операциями." @("JavaScript","Async") @("Callback","Async Await") @()
New-Zettel "JS PROTOTYPE" "# JS PROTOTYPE #javascript #oop #inheritance #уровень1" "Механизм наследования через цепочку прототипов." @("JavaScript","OOP") @("Class Syntax","JS CLOSURES") @()
New-Zettel "JS EVENT LOOP" "# JS EVENT LOOP #javascript #async #runtime #уровень1" "Обработка асинхронных событий в однопоточном JavaScript." @("JavaScript","Runtime") @("Web Workers","Service Workers") @()
New-Zettel "TS GENERICS" "# TS GENERICS #typescript #types #generics #уровень1" "Параметризованные типы для переиспользуемых компонентов." @("TypeScript","Static Typing") @("TS UTILITY TYPES","TS INFERENCE") @()
New-Zettel "TS UTILITY TYPES" "# TS UTILITY TYPES #typescript #types #utility #уровень1" "Partial, Pick, Omit, Record - встроенные утилитарные типы." @("TypeScript","Type System") @("TS GENERICS","Mapped Types") @()
New-Zettel "PYTHON DECORATOR" "# PYTHON DECORATOR #python #metaprogramming #decorator #уровень1" "Функция высшего порядка для модификации поведения функций." @("Python","Metaprogramming") @("Context Manager","Descriptor") @()
New-Zettel "PYTHON GENERATOR" "# PYTHON GENERATOR #python #iteration #lazy #уровень1" "Функция с yield для ленивой генерации последовательностей." @("Python","Iteration") @("Iterator","Coroutines") @()
New-Zettel "JAVA GC" "# JAVA GC #java #jvm #memory #уровень1" "Автоматическое управление памятью в JVM через сборщик мусора." @("Java","JVM") @("Memory Management","C# GC") @()
New-Zettel "JAVA STREAMS" "# JAVA STREAMS #java #functional #collections #уровень1" "Функциональная обработка коллекций через stream pipeline." @("Java","Functional") @("Lambda","Optional") @()
New-Zettel "GO ROUTINES" "# GO ROUTINES #go #concurrency #goroutines #уровень1" "Легковесные потоки в Go для конкурентного выполнения." @("Go","Concurrency") @("Channels","Select") @()
New-Zettel "RUST OWNERSHIP" "# RUST OWNERSHIP #rust #memory #safety #уровень1" "Правила владения памятью в Rust без сборщика мусора." @("Rust","Systems") @("C++ RAII","JAVA GC") @()
New-Zettel "RUST BORROWING" "# RUST BORROWING #rust #references #lifetimes #уровень1" "Заимствование ссылок с проверкой времен жизни в Rust." @("Rust","Memory Safety") @("RUST OWNERSHIP") @()
New-Zettel "KOTLIN COROUTINES" "# KOTLIN COROUTINES #kotlin #async #coroutines #уровень1" "Легковесные асинхронные задачи с suspend функциями." @("Kotlin","Async") @("GO ROUTINES","JS PROMISE") @()
New-Zettel "SWIFT OPTIONALS" "# SWIFT OPTIONALS #swift #types #safety #уровень1" "Тип Optional для безопасной работы с nil значениями." @("Swift","Type System") @("TS GENERICS","KOTLIN NULL SAFETY") @()
New-Zettel "RUST TRAITS" "# RUST TRAITS #rust #generics #interfaces #уровень1" "Определение общего поведения для типов через traits." @("Rust","Type System") @("RUST OWNERSHIP","TS GENERICS") @()
New-Zettel "TYPESCRIPT DECORATORS" "# TYPESCRIPT DECORATORS #typescript #metaprogramming #decorator #уровень1" "Декораторы классов и методов в TypeScript." @("TypeScript","Metaprogramming") @("PYTHON DECORATOR","TS GENERICS") @()
New-Zettel "C# LINQ" "# C# LINQ #csharp #dotnet #query #уровень1" "Language Integrated Query для работы с коллекциями в C#." @("C#",".NET") @("JAVA STREAMS","SQL") @()
New-Zettel "PHP COMPOSER" "# PHP COMPOSER #php #dependencies #package #уровень1" "Менеджер зависимостей для PHP приложений." @("PHP","Package Management") @("NPM","PIP") @()

# ===== SECURITY =====
New-Zettel "XSS" "# XSS #security #web #injection #уровень1" "Cross-Site Scripting - внедрение скриптов в веб-страницы." @("Web Security","OWASP") @("CSRF","SQL INJECTION") @()
New-Zettel "SQL INJECTION" "# SQL INJECTION #security #database #injection #уровень1" "Внедрение SQL кода через неэкранированный пользовательский ввод." @("Web Security","Database") @("XSS","Command Injection") @()
New-Zettel "CSRF" "# CSRF #security #web #forgery #уровень1" "Cross-Site Request Forgery - подделка межсайтовых запросов." @("Web Security","OWASP") @("XSS","SSRF") @()
New-Zettel "SSL TLS" "# SSL TLS #security #cryptography #protocol #уровень1" "Протокол шифрования данных между клиентом и сервером." @("Cryptography","Network Security") @("HTTPS","SSH") @()
New-Zettel "HASHING" "# HASHING #security #cryptography #hash #уровень1" "Однонаправленные хеш-функции для целостности данных." @("Cryptography","Security") @("Encryption Symmetric","Encryption Asymmetric") @()
New-Zettel "ENCRYPTION SYMMETRIC" "# ENCRYPTION SYMMETRIC #security #cryptography #aes #уровень1" "Шифрование одним ключом: AES, DES, ChaCha20." @("Cryptography","Data Protection") @("ENCRYPTION ASYMMETRIC","HASHING") @()
New-Zettel "ENCRYPTION ASYMMETRIC" "# ENCRYPTION ASYMMETRIC #security #cryptography #rsa #уровень1" "Шифрование парой ключей: публичный и приватный." @("Cryptography","Data Protection") @("ENCRYPTION SYMMETRIC","SSL TLS") @()
New-Zettel "OWASP TOP 10" "# OWASP TOP 10 #security #owasp #vulnerabilities #уровень1" "Список 10 самых критичных уязвимостей веб-приложений." @("Web Security","Standards") @("XSS","SQL INJECTION","CSRF") @()
New-Zettel "RBAC" "# RBAC #security #authorization #access #уровень1" "Role-Based Access Control - доступ на основе ролей." @("Authorization","Access Control") @("ABAC","ACL") @()
New-Zettel "CSP" "# CSP #security #http #headers #уровень1" "Content Security Policy - защита от XSS через HTTP заголовок." @("Browser Security","HTTP") @("CORS","XSS") @()
New-Zettel "SSRF" "# SSRF #security #web #server-side #уровень1" "Server-Side Request Forgery - подделка запросов на стороне сервера." @("Web Security","OWASP") @("CSRF","XSS") @()
New-Zettel "IDOR" "# IDOR #security #access-control #api #уровень1" "Insecure Direct Object Reference - небезопасные прямые ссылки." @("Access Control","API Security") @("RBAC","OWASP TOP 10") @()
New-Zettel "SECRETS MANAGEMENT" "# SECRETS MANAGEMENT #security #infrastructure #devops #уровень1" "Хранение и ротация секретов, ключей и паролей." @("Security","DevOps") @("HASHING","ENCRYPTION SYMMETRIC") @()
New-Zettel "ZERO TRUST" "# ZERO TRUST #security #architecture #network #уровень1" "Модель безопасности без доверия никому внутри сети." @("Security Architecture","Network") @("RBAC","SSL TLS") @()
New-Zettel "WAF" "# WAF #security #web #firewall #уровень1" "Web Application Firewall - фильтрация HTTP трафика." @("Web Security","Infrastructure") @("CSP","OWASP TOP 10") @()

# ===== NETWORKING =====
New-Zettel "OSI MODEL" "# OSI MODEL #networking #protocols #layers #уровень1" "Семиуровневая модель сетевого взаимодействия." @("Networking","Protocols") @("TCP IP MODEL") @()
New-Zettel "TCP IP MODEL" "# TCP IP MODEL #networking #protocols #tcp #уровень1" "Набор протоколов TCP, IP, UDP, ICMP для передачи данных." @("Networking","Internet") @("OSI MODEL") @()
New-Zettel "DNS" "# DNS #networking #dns #domain #уровень1" "Преобразование доменных имен в IP адреса." @("Networking","DNS") @("HTTP Protocol","CDN") @()
New-Zettel "HTTP2" "# HTTP2 #http #protocol #performance #уровень1" "HTTP/2 с мультиплексированием и Server Push." @("HTTP Protocol","Performance") @("HTTP1.1","HTTP3") @()
New-Zettel "HTTP3" "# HTTP3 #http #protocol #quic #уровень1" "HTTP/3 поверх QUIC для снижения задержек." @("HTTP Protocol","Performance") @("HTTP2","QUIC") @()
New-Zettel "CDN" "# CDN #networking #performance #caching #уровень1" "Content Delivery Network - распределенная сеть кэширования." @("Performance","Networking") @("CACHING STRATEGY","DNS") @()
New-Zettel "REVERSE PROXY" "# REVERSE PROXY #networking #architecture #proxy #уровень1" "Прокси-сервер перед группой бэкендов." @("Networking","Architecture") @("Load Balancer","API GATEWAY") @()
New-Zettel "SUBNET" "# SUBNET #networking #ip #cidr #уровень1" "Разделение IP сети на подсети с маской." @("Networking","IP Addressing") @("NAT","CIDR") @()
New-Zettel "NAT" "# NAT #networking #ip #translation #уровень1" "Network Address Translation - преобразование IP адресов." @("Networking","IP") @("SUBNET","FIREWALL") @()
New-Zettel "FIREWALL" "# FIREWALL #networking #security #filtering #уровень1" "Фильтрация трафика по IP, портам и протоколам." @("Network Security","Infrastructure") @("NAT","WAF") @()
New-Zettel "TCP HANDSHAKE" "# TCP HANDSHAKE #networking #tcp #connection #уровень1" "Трехэтапное рукопожатие SYN SYN-ACK ACK для установки TCP соединения." @("TCP","Networking") @("TCP IP MODEL","SSL TLS") @()
New-Zettel "UDP PROTOCOL" "# UDP PROTOCOL #networking #udp #connectionless #уровень1" "Протокол без установки соединения для стриминга и игр." @("Transport Layer","Networking") @("TCP HANDSHAKE","HTTP3") @()
New-Zettel "QUIC PROTOCOL" "# QUIC PROTOCOL #networking #transport #http3 #уровень1" "Протокол на UDP с мультиплексированием и 0-RTT." @("Transport","Performance") @("UDP PROTOCOL","HTTP3") @()
New-Zettel "BGP" "# BGP #networking #routing #protocol #уровень1" "Border Gateway Protocol - маршрутизация между автономными системами." @("Routing","Internet") @("OSI MODEL","FIREWALL") @()
New-Zettel "MPLS" "# MPLS #networking #routing #carrier #уровень1" "Multiprotocol Label Switching - маршрутизация по меткам." @("Routing","Carrier") @("BGP","OSI MODEL") @()
New-Zettel "VLAN" "# VLAN #networking #switching #segmentation #уровень1" "Virtual LAN - логическое разделение сети на уровне L2." @("Switching","Segmentation") @("SUBNET","FIREWALL") @()
New-Zettel "NETWORK TUNNEL" "# NETWORK TUNNEL #networking #vpn #encapsulation #уровень1" "Туннелирование трафика через VPN, GRE, IPsec." @("Networking","Security") @("SSL TLS","NAT") @()

# ===== TESTING =====
New-Zettel "UNIT TESTING" "# UNIT TESTING #testing #quality #unit #уровень1" "Тестирование отдельных модулей кода в изоляции." @("QA","Development") @("INTEGRATION TESTING","E2E TESTING") @()
New-Zettel "INTEGRATION TESTING" "# INTEGRATION TESTING #testing #quality #integration #уровень1" "Тестирование взаимодействия между компонентами системы." @("QA","Development") @("UNIT TESTING","E2E TESTING") @()
New-Zettel "E2E TESTING" "# E2E TESTING #testing #quality #e2e #уровень1" "Сквозное тестирование пользовательских сценариев." @("QA","Automation") @("INTEGRATION TESTING","UNIT TESTING") @()
New-Zettel "TDD" "# TDD #testing #methodology #tdd #уровень1" "Test-Driven Development: сначала тест, потом код." @("Methodology","Quality") @("BDD","UNIT TESTING") @()
New-Zettel "MOCK" "# MOCK #testing #patterns #isolation #уровень1" "Имитация зависимости для изолированного тестирования модуля." @("Testing Patterns","Unit Testing") @("Stub","Fake") @()
New-Zettel "PERFORMANCE TESTING" "# PERFORMANCE TESTING #testing #performance #load #уровень1" "Тестирование скорости и стабильности под нагрузкой." @("QA","Performance") @("LOAD TESTING","STRESS TESTING") @()
New-Zettel "CODE COVERAGE" "# CODE COVERAGE #testing #quality #metrics #уровень1" "Метрика процента кода, покрытого тестами." @("QA","Metrics") @("Mutation Testing","UNIT TESTING") @()
New-Zettel "BDD" "# BDD #testing #methodology #behavior #уровень1" "Behavior-Driven Development через сценарии Given-When-Then." @("Methodology","QA") @("TDD","E2E TESTING") @()
New-Zettel "SNAPSHOT TESTING" "# SNAPSHOT TESTING #testing #ui #visual #уровень1" "Сравнение UI компонентов с сохраненными снепшотами." @("Testing","UI") @("UNIT TESTING","E2E TESTING") @()
New-Zettel "CONTRACT TESTING" "# CONTRACT TESTING #testing #microservices #api #уровень1" "Проверка контрактов между микросервисами." @("Testing","Microservices") @("INTEGRATION TESTING","E2E TESTING") @()
New-Zettel "CHAOS ENGINEERING" "# CHAOS ENGINEERING #testing #resilience #reliability #уровень1" "Экспериментальное тестирование отказоустойчивости системы." @("Resilience","QA") @("PERFORMANCE TESTING","SITE RELIABILITY") @()
New-Zettel "FUZZ TESTING" "# FUZZ TESTING #testing #security #automation #уровень1" "Автоматическая генерация случайных данных для поиска уязвимостей." @("Testing","Security") @("UNIT TESTING","SECURITY") @()

# ===== STATE MANAGEMENT =====
New-Zettel "REDUX STORE" "# REDUX STORE #redux #state-management #store #уровень1" "Глобальное хранилище с иммутабельными обновлениями и reducers." @("State Management","Redux") @("REACT CONTEXT","MOBX") @()
New-Zettel "REDUX MIDDLEWARE" "# REDUX MIDDLEWARE #redux #async #reactive #уровень1" "Middleware для обработки асинхронных действий в Redux." @("Redux","Async") @("REDUX STORE","Thunk") @()
New-Zettel "MOBX" "# MOBX #state-management #reactive #observable #уровень1" "Реактивное управление состоянием через observable потоки." @("State Management","Reactive") @("REDUX STORE","ZUSTAND") @()
New-Zettel "ZUSTAND" "# ZUSTAND #state-management #lightweight #hooks #уровень1" "Легковесное управление состоянием с минимальным boilerplate." @("State Management","Frontend") @("REDUX STORE","MOBX") @()
New-Zettel "LOCAL STORAGE" "# LOCAL STORAGE #browser #storage #persistence #уровень1" "Хранилище ключ-значение в браузере до 5MB." @("Browser Storage","Web APIs") @("Session Storage","IndexedDB") @()
New-Zettel "INDEXEDDB" "# INDEXEDDB #browser #storage #nosql #уровень1" "NoSQL БД в браузере для больших объемов данных." @("Browser Storage","Offline") @("LOCAL STORAGE","Web SQL") @()
New-Zettel "SERVICE WORKERS" "# SERVICE WORKERS #pwa #offline #cache #уровень1" "Фоновые скрипты для перехвата запросов и кэширования." @("PWA","Offline") @("Web Workers","Cache API") @()
New-Zettel "PWA" "# PWA #pwa #mobile #web #app #уровень1" "Progressive Web App - веб-приложение с нативными возможностями." @("PWA","Mobile") @("SERVICE WORKERS","Manifest") @()
New-Zettel "WEB WORKERS" "# WEB WORKERS #browser #multithreading #performance #уровень1" "Многопоточность в браузере для фоновых вычислений." @("Browser APIs","Performance") @("SERVICE WORKERS","JS EVENT LOOP") @()
New-Zettel "SESSION STORAGE" "# SESSION STORAGE #browser #storage #temporary #уровень1" "Временное хранилище в браузере на время вкладки." @("Browser Storage","Web APIs") @("LOCAL STORAGE","INDEXEDDB") @()

# ===== AGILE & MANAGEMENT =====
New-Zettel "SCRUM" "# SCRUM #agile #methodology #framework #уровень1" "Фреймворк итеративной разработки с Sprint до 4 недель." @("Agile","Management") @("KANBAN","Waterfall") @()
New-Zettel "KANBAN" "# KANBAN #agile #visualization #flow #уровень1" "Визуализация потока задач с WIP лимитами." @("Agile","Process") @("SCRUM") @()
New-Zettel "CODE REVIEW" "# CODE REVIEW #quality #collaboration #process #уровень1" "Проверка кода коллегами перед слиянием." @("Development Practices","Quality") @("Pair Programming","Static Analysis") @()
New-Zettel "GIT BRANCHING" "# GIT BRANCHING #git #vcs #strategy #уровень1" "Стратегии ветвления: GitFlow, Trunk-Based, Feature branches." @("Version Control","Collaboration") @("CODE REVIEW","CI/CD PIPELINE") @()
New-Zettel "GIT REBASE" "# GIT REBASE #git #vcs #history #clean #уровень1" "Перемещение коммитов на новую базу для чистой истории." @("Version Control","Git") @("GIT MERGE","GIT BRANCHING") @()
New-Zettel "GIT MERGE" "# GIT MERGE #git #vcs #integration #уровень1" "Слияние веток с сохранением полной истории." @("Version Control","Git") @("GIT REBASE","GIT BRANCHING") @()
New-Zettel "MICROSERVICES" "# MICROSERVICES #architecture #distributed #services #уровень1" "Независимо развертываемые сервисы с собственной БД." @("Software Architecture","Distributed") @("MONOLITH","SERVICE MESH") @()
New-Zettel "MONOLITH" "# MONOLITH #architecture #pattern #single #уровень1" "Единое приложение со всеми компонентами в одном процессе." @("Software Architecture","Patterns") @("MICROSERVICES","Modular Monolith") @()
New-Zettel "DDD" "# DDD #architecture #domain #modeling #уровень1" "Domain-Driven Design - проектирование через предметную область." @("Architecture","Modeling") @("MICROSERVICES","CLEAN ARCHITECTURE") @()
New-Zettel "CLEAN ARCHITECTURE" "# CLEAN ARCHITECTURE #architecture #layers #independence #уровень1" "Архитектура с независимостью от фреймворков, БД и UI." @("Architecture","Principles") @("DDD","Onion Architecture") @()
New-Zettel "CQRS" "# CQRS #architecture #pattern #commands #queries #уровень1" "Command Query Responsibility Segregation - разделение чтения и записи." @("Architecture","Patterns") @("EVENT DRIVEN","DDD") @()
New-Zettel "EVENT SOURCING" "# EVENT SOURCING #architecture #events #persistence #уровень1" "Хранение всех изменений как последовательности событий." @("Architecture","Patterns") @("CQRS","EVENT DRIVEN") @()
New-Zettel "SAGA PATTERN" "# SAGA PATTERN #architecture #distributed #transactions #уровень1" "Управление распределенными транзакциями через компенсации." @("Microservices","Transactions") @("CQRS","EVENT SOURCING") @()
New-Zettel "SERVICE MESH" "# SERVICE MESH #architecture #microservices #networking #уровень1" "Инфраструктурный слой для коммуникации микросервисов." @("Microservices","Networking") @("MICROSERVICES","KUBERNETES SERVICE") @()
New-Zettel "TWELVE FACTOR APP" "# TWELVE FACTOR APP #architecture #methodology #saas #уровень1" "Методология создания SaaS приложений с 12 принципами." @("Architecture","Methodology") @("CLEAN ARCHITECTURE","MICROSERVICES") @()
New-Zettel "API FIRST" "# API FIRST #api #design #methodology #уровень1" "Подход с проектированием API до написания кода." @("API Design","Methodology") @("SWAGGER OPENAPI","REST ENDPOINT") @()
New-Zettel "AGILE MANIFESTO" "# AGILE MANIFESTO #agile #values #principles #уровень1" "Четыре ценности и 12 принципов Agile разработки." @("Agile","Methodology") @("SCRUM","KANBAN") @()

# ===== DATABASE - ADVANCED =====
New-Zettel "SQL TUNING" "# SQL TUNING #database #performance #optimization #уровень1" "Оптимизация SQL запросов с execution plan и индексами." @("SQL Performance","Database Admin") @("DB INDEX","SQL WINDOW FUNCTION") @()
New-Zettel "GRAPH DATABASE" "# GRAPH DATABASE #database #nosql #graph #уровень1" "БД на графовой структуре для связанных данных." @("NoSQL","Data Modeling") @("NOSQL DOCUMENT","NOSQL KEY-VALUE") @()
New-Zettel "TIME SERIES DB" "# TIME SERIES DB #database #timeseries #metrics #уровень1" "БД для хранения временных рядов метрик." @("Database","Monitoring") @("PROMETHEUS","InfluxDB") @()
New-Zettel "COLUMNAR DB" "# COLUMNAR DB #database #analytics #olap #уровень1" "Колоночная БД для аналитических запросов." @("Database","Analytics") @("NOSQL DOCUMENT","SQL GROUP BY") @()
New-Zettel "DATABASE BACKUP" "# DATABASE BACKUP #database #disaster-recovery #ops #уровень1" "Стратегии бэкапа: полный, инкрементальный, differential." @("Database Admin","Ops") @("DB REPLICATION") @()
New-Zettel "DATABASE MIGRATION" "# DATABASE MIGRATION #database #schema #devops #уровень1" "Управление изменениями схемы БД через миграции." @("Database","DevOps") @("SQL VIEW","STORED PROCEDURE") @()
New-Zettel "ORM" "# ORM #database #backend #abstraction #уровень1" "Object-Relational Mapping - абстракция БД через объекты." @("Backend","Database") @("SQL JOIN TYPES","N+1 QUERY") @()
New-Zettel "CONNECTION POOL" "# CONNECTION POOL #database #performance #scalability #уровень1" "Пул соединений с БД для снижения накладных расходов." @("Database","Performance") @("LOAD BALANCING") @()
New-Zettel "DATABASE AUDIT" "# DATABASE AUDIT #database #security #compliance #уровень1" "Логирование всех операций с БД для аудита." @("Database","Security") @("RBAC","DATABASE BACKUP") @()

# ===== SOFTWARE ARCHITECTURE =====
New-Zettel "REPOSITORY PATTERN" "# REPOSITORY PATTERN #architecture #patterns #data #уровень1" "Абстракция доступа к данным, скрывающая детали хранения." @("Design Patterns","Architecture") @("DI CONTAINER","CLEAN ARCHITECTURE") @()
New-Zettel "UNIT OF WORK" "# UNIT OF WORK #architecture #patterns #transactions #уровень1" "Группировка операций в одну транзакцию с фиксацией изменений." @("Design Patterns","Data") @("REPOSITORY PATTERN","DI CONTAINER") @()
New-Zettel "MVC PATTERN" "# MVC PATTERN #architecture #pattern #ui #уровень1" "Model-View-Controller - разделение данных, отображения и логики." @("Architecture","UI Patterns") @("MVVM","CLEAN ARCHITECTURE") @()
New-Zettel "MVVM" "# MVVM #architecture #pattern #ui #frontend #уровень1" "Model-View-ViewModel для реактивных UI приложений." @("Architecture","UI Patterns") @("MVC PATTERN","REACT CONTEXT") @()
New-Zettel "PIPELINE PATTERN" "# PIPELINE PATTERN #architecture #patterns #data #processing #уровень1" "Последовательная обработка данных через стадии конвейера." @("Architecture","Data Processing") @("CHAIN OF RESPONSIBILITY","STREAM PROCESSING") @()
New-Zettel "STRANGER FIG" "# STRANGER FIG #architecture #refactoring #migration #уровень1" "Постепенная замена монолита микросервисами через фасад." @("Architecture","Migration") @("MICROSERVICES","MONOLITH") @()
New-Zettel "CIRCUIT BREAKER" "# CIRCUIT BREAKER #architecture #resilience #fault-tolerance #уровень1" "Предотвращение каскадных отказов через размыкание цепи." @("Resilience","Patterns") @("BACKPRESSURE","BULKHEAD") @()
New-Zettel "BULKHEAD" "# BULKHEAD #architecture #resilience #isolation #уровень1" "Изоляция ресурсов для предотвращения отказа всей системы." @("Resilience","Patterns") @("CIRCUIT BREAKER","MICROSERVICES") @()
New-Zettel "RETRY PATTERN" "# RETRY PATTERN #architecture #resilience #distributed #уровень1" "Повторная попытка выполнения операции при временном отказе." @("Resilience","Patterns") @("CIRCUIT BREAKER","BACKPRESSURE") @()
New-Zettel "IDEMPOTENCY" "# IDEMPOTENCY #architecture #api #distributed #уровень1" "Гарантия, что повторный запрос дает тот же результат." @("API Design","Distributed") @("RETRY PATTERN","REST ENDPOINT") @()

# ===== MOBILE DEVELOPMENT =====
New-Zettel "ANDROID ACTIVITY" "# ANDROID ACTIVITY #android #lifecycle #ui #уровень1" "Компонент с жизненным циклом для экрана в Android." @("Android","Mobile") @("iOS ViewController","COMPONENT LIFECYCLE") @()
New-Zettel "ANDROID FRAGMENT" "# ANDROID FRAGMENT #android #ui #modular #уровень1" "Переиспользуемый фрагмент UI внутри Activity." @("Android","UI") @("ANDROID ACTIVITY","REACT COMPONENT") @()
New-Zettel "SWIFT UI" "# SWIFT UI #ios #swift #declarative #уровень1" "Декларативный фреймворк для UI на iOS." @("iOS","Swift") @("UIKit","REACT HOOKS") @()
New-Zettel "FLUTTER WIDGET" "# FLUTTER WIDGET #flutter #dart #ui #уровень1" "Виджеты как строительные блоки UI во Flutter." @("Flutter","Mobile") @("REACT COMPONENT","SWIFT UI") @()
New-Zettel "REACT NATIVE" "# REACT NATIVE #react-native #mobile #cross-platform #уровень1" "Создание нативных мобильных приложений на React." @("Mobile","Cross-platform") @("REACT HOOKS","FLUTTER WIDGET") @()
New-Zettel "MOBILE APP ARCH" "# MOBILE APP ARCH #mobile #architecture #patterns #уровень1" "Архитектурные паттерны мобильных приложений: MVP, MVVM, MVI." @("Mobile","Architecture") @("MVVM","CLEAN ARCHITECTURE") @()
New-Zettel "APP BUNDLE" "# APP BUNDLE #android #distribution #size #уровень1" "Формат публикации Android App Bundle для оптимизации размера." @("Android","Distribution") @("APK","PWA") @()
New-Zettel "IOS APP STORE" "# IOS APP STORE #ios #distribution #review #уровень1" "Процесс публикации приложения в App Store с ревью." @("iOS","Distribution") @("APP BUNDLE","TestFlight") @()

# ===== DATABASE - NOSQL =====
New-Zettel "MONGODB AGGREGATION" "# MONGODB AGGREGATION #nosql #mongodb #pipeline #уровень1" "Конвейер обработки документов для аналитики в MongoDB." @("MongoDB","NoSQL") @("SQL WINDOW FUNCTION","MAP REDUCE") @()
New-Zettel "REDIS CACHE" "# REDIS CACHE #redis #caching #performance #уровень1" "Кэширование данных в памяти с Redis для высокой скорости." @("Caching","Performance") @("CACHING STRATEGY","MEMCACHED") @()
New-Zettel "CASSANDRA NODES" "# CASSANDRA NODES #nosql #cassandra #distributed #уровень1" "Распределенная NoSQL БД с peer-to-peer архитектурой." @("NoSQL","Distributed") @("NOSQL DOCUMENT","DB SHARDING") @()
New-Zettel "DYNAMODB TABLES" "# DYNAMODB TABLES #nosql #aws #serverless #уровень1" "Управляемая NoSQL БД от AWS с ключом и сортировкой." @("AWS","NoSQL") @("CASSANDRA NODES","MONGODB AGGREGATION") @()
New-Zettel "NEO4J GRAPH" "# NEO4J GRAPH #nosql #graph #cypher #уровень1" "Graph БД с языком запросов Cypher для связанных данных." @("Graph Database","NoSQL") @("NOSQL DOCUMENT","SQL JOIN TYPES") @()
New-Zettel "INFLUXDB" "# INFLUXDB #timeseries #metrics #monitoring #уровень1" "БД временных рядов для метрик систем мониторинга." @("Time Series","Database") @("PROMETHEUS","TIME SERIES DB") @()
New-Zettel "ELASTICSEARCH" "# ELASTICSEARCH #search #nosql #fulltext #уровень1" "Поисковый движок с полнотекстовым поиском и аналитикой." @("Search","NoSQL") @("MONGODB AGGREGATION","ELASTIC STACK") @()

# ===== CLOUD =====
New-Zettel "AWS EC2" "# AWS EC2 #aws #compute #cloud #уровень1" "Виртуальные серверы в облаке AWS с различными инстансами." @("AWS","Compute") @("AWS Lambda","DOCKER CONTAINER") @()
New-Zettel "AWS LAMBDA" "# AWS LAMBDA #aws #serverless #compute #уровень1" "Serverless функции, запускаемые по событиям." @("AWS","Serverless") @("AWS EC2","Azure Functions") @()
New-Zettel "AWS S3" "# AWS S3 #aws #storage #object #уровень1" "Объектное хранилище для файлов и бэкапов." @("AWS","Storage") @("CDN","Static Hosting") @()
New-Zettel "AWS RDS" "# AWS RDS #aws #database #managed #уровень1" "Управляемые реляционные БД в AWS." @("AWS","Database") @("DB REPLICATION","AWS DYNAMODB") @()
New-Zettel "KUBERNETES EKS" "# KUBERNETES EKS #aws #kubernetes #managed #уровень1" "Управляемый Kubernetes кластер на AWS." @("AWS","Kubernetes") @("KUBECTL","HELM") @()
New-Zettel "AZURE DEVOPS" "# AZURE DEVOPS #azure #devops #pipeline #уровень1" "Платформа CI/CD и управление проектами от Microsoft." @("Azure","DevOps") @("JENKINS","GITHUB ACTIONS") @()
New-Zettel "GCP GKE" "# GCP GKE #gcp #kubernetes #google #уровень1" "Управляемый Kubernetes на Google Cloud Platform." @("GCP","Kubernetes") @("KUBERNETES EKS","KUBECTL") @()
New-Zettel "CLOUD NATIVE" "# CLOUD NATIVE #cloud #architecture #best-practices #уровень1" "Архитектура приложений, спроектированных для облака." @("Cloud","Architecture") @("TWELVE FACTOR APP","MICROSERVICES") @()
New-Zettel "INFRA AS CODE" "# INFRA AS CODE #devops #automation #cloud #уровень1" "Управление инфраструктурой через декларативные конфиги." @("DevOps","Cloud") @("TERRAFORM","ANSIBLE") @()

# ===== DATA ENGINEERING =====
New-Zettel "ETL PIPELINE" "# ETL PIPELINE #data #etl #pipeline #уровень1" "Extract, Transform, Load - извлечение, преобразование, загрузка." @("Data Engineering","Pipeline") @("PIPELINE PATTERN","STREAM PROCESSING") @()
New-Zettel "DATA WAREHOUSE" "# DATA WAREHOUSE #data #analytics #storage #уровень1" "Централизованное хранилище данных для отчетности." @("Data Engineering","Analytics") @("ETL PIPELINE","COLUMNAR DB") @()
New-Zettel "DATA LAKE" "# DATA LAKE #data #storage #raw #уровень1" "Хранилище сырых данных в оригинальном формате." @("Data Engineering","Storage") @("DATA WAREHOUSE","AWS S3") @()
New-Zettel "STREAM PROCESSING" "# STREAM PROCESSING #data #streaming #realtime #уровень1" "Обработка потоков данных в реальном времени." @("Data Engineering","Realtime") @("EVENT DRIVEN","Kafka") @()
New-Zettel "MAP REDUCE" "# MAP REDUCE #data #distributed #computation #уровень1" "Распределенная обработка больших данных через map и reduce." @("Data Engineering","Distributed") @("STREAM PROCESSING","NOSQL DOCUMENT") @()
New-Zettel "APACHE SPARK" "# APACHE SPARK #data #distributed #computation #уровень1" "Движок распределенной обработки данных в памяти." @("Data Engineering","Distributed") @("MAP REDUCE","STREAM PROCESSING") @()
New-Zettel "DAG AIRFLOW" "# DAG AIRFLOW #data #orchestration #pipeline #уровень1" "Оркестрация пайплайнов через направленные ациклические графы." @("Data Engineering","Orchestration") @("ETL PIPELINE","CI/CD PIPELINE") @()
New-Zettel "KAFKA" "# KAFKA #data #streaming #message-broker #уровень1" "Распределенный брокер сообщений для потоковых данных." @("Data Engineering","Streaming") @("MESSAGE QUEUE","STREAM PROCESSING") @()

# ===== MACHINE LEARNING =====
New-Zettel "SUPERVISED LEARNING" "# SUPERVISED LEARNING #ml #supervised #training #уровень1" "Обучение с учителем на размеченных данных для предсказаний." @("Machine Learning","AI") @("UNSUPERVISED LEARNING","REINFORCEMENT") @()
New-Zettel "UNSUPERVISED LEARNING" "# UNSUPERVISED LEARNING #ml #unsupervised #clustering #уровень1" "Обучение без учителя для поиска скрытых паттернов." @("Machine Learning","AI") @("SUPERVISED LEARNING","DIMENSIONALITY") @()
New-Zettel "NEURAL NETWORK" "# NEURAL NETWORK #ml #deep-learning #layers #уровень1" "Искусственные нейронные сети с множеством слоев." @("Deep Learning","AI") @("SUPERVISED LEARNING","CNN") @()
New-Zettel "CNN" "# CNN #ml #computer-vision #convolution #уровень1" "Сверточные нейронные сети для анализа изображений." @("Deep Learning","Computer Vision") @("NEURAL NETWORK","RNN") @()
New-Zettel "RNN" "# RNN #ml #sequence #recurrent #уровень1" "Рекуррентные нейронные сети для последовательных данных." @("Deep Learning","Sequences") @("NEURAL NETWORK","TRANSFORMER") @()
New-Zettel "TRANSFORMER" "# TRANSFORMER #ml #attention #nlp #уровень1" "Архитектура с механизмом внимания для NLP." @("Deep Learning","NLP") @("RNN","ATTENTION") @()
New-Zettel "REGRESSION" "# REGRESSION #ml #statistics #prediction #уровень1" "Предсказание непрерывных значений через регрессию." @("Machine Learning","Statistics") @("SUPERVISED LEARNING","CLASSIFICATION") @()
New-Zettel "CLASSIFICATION" "# CLASSIFICATION #ml #supervised #labels #уровень1" "Отнесение объектов к категориям на основе признаков." @("Machine Learning","Supervised") @("REGRESSION","SUPERVISED LEARNING") @()
New-Zettel "OVERFITTING" "# OVERFITTING #ml #training #regularization #уровень1" "Модель запоминает шум вместо общих закономерностей." @("Machine Learning","Training") @("REGULARIZATION","CROSS-VALIDATION") @()
New-Zettel "GRADIENT DESCENT" "# GRADIENT DESCENT #ml #optimization #training #уровень1" "Итеративная оптимизация через градиент функции потерь." @("Machine Learning","Optimization") @("STOCHASTIC GD","BACKPROPAGATION") @()
New-Zettel "BACKPROPAGATION" "# BACKPROPAGATION #ml #neural-net #gradient #уровень1" "Распространение градиента ошибки обратно по сети." @("Deep Learning","Training") @("GRADIENT DESCENT","NEURAL NETWORK") @()

# ===== PROTOCOLS & FORMATS =====
New-Zettel "JSON FORMAT" "# JSON FORMAT #protocols #data #serialization #уровень1" "Легковесный формат обмена данными на основе JavaScript." @("Data Formats","Serialization") @("XML","YAML","PROTOBUF") @()
New-Zettel "XML" "# XML #protocols #data #markup #уровень1" "Расширяемый язык разметки для структурированных данных." @("Data Formats","Markup") @("JSON FORMAT","HTML SEMANTIC") @()
New-Zettel "PROTOBUF" "# PROTOBUF #protocols #serialization #binary #уровень1" "Бинарная сериализация структур от Google." @("Serialization","Performance") @("JSON FORMAT","GRPC") @()
New-Zettel "GRPC" "# GRPC #api #rpc #protobuf #уровень1" "Высокопроизводительный RPC фреймворк от Google." @("API","RPC") @("RPC PROTOCOL","PROTOBUF") @()
New-Zettel "YAML" "# YAML #config #data #serialization #уровень1" "Человекочитаемый формат для конфигурационных файлов." @("Data Formats","Config") @("JSON FORMAT","TOML") @()
New-Zettel "GRAPHQL SUBSCRIPTIONS" "# GRAPHQL SUBSCRIPTIONS #graphql #realtime #events #уровень1" "Подписки GraphQL для получения данных в реальном времени." @("GraphQL","Realtime") @("GRAPHQL SCHEMA","WEBSOCKET") @()
New-Zettel "OPEN TELEMETRY" "# OPEN TELEMETRY #observability #tracing #metrics #уровень1" "Стандарт сбора трассировок, метрик и логов." @("Observability","Standards") @("PROMETHEUS","ELASTIC STACK") @()
New-Zettel "WEBHOOK" "# WEBHOOK #api #events #callback #уровень1" "HTTP колбэк для уведомления о событиях между системами." @("API","Integration") @("WEBSOCKET","POLLING") @()
New-Zettel "SSE" "# SSE #api #realtime #streaming #уровень1" "Server-Sent Events - однонаправленный стриминг от сервера." @("Realtime","Web") @("WEBSOCKET","WEBHOOK") @()
New-Zettel "SERVERLESS" "# SERVERLESS #cloud #architecture #lambda #уровень1" "Модель без управления серверами с оплатой за вызовы." @("Cloud","Architecture") @("AWS LAMBDA","FaaS") @()
New-Zettel "EDGE COMPUTING" "# EDGE COMPUTING #infrastructure #performance #iot #уровень1" "Вычисления на границе сети рядом с пользователем." @("Infrastructure","Performance") @("CDN","SERVERLESS") @()
New-Zettel "WASM" "# WASM #wasm #performance #browser #уровень1" "WebAssembly - бинарный формат для高性能 кода в браузере." @("Browser","Performance") @("JS EVENT LOOP","WEB WORKERS") @()
New-Zettel "CRDT" "# CRDT #distributed #conflict #replication #уровень1" "Conflict-free Replicated Data Types для согласованных данных." @("Distributed","Data") @("EVENT SOURCING","CQRS") @()
New-Zettel "SWAGGER CODEGEN" "# SWAGGER CODEGEN #api #openapi #generation #уровень1" "Генерация клиентов и серверов из OpenAPI спецификации." @("API","Tools") @("SWAGGER OPENAPI","API FIRST") @()
New-Zettel "FEATURE FLAGS" "# FEATURE FLAGS #development #deployment #testing #уровень1" "Флаги для включения функций без деплоя." @("Development","Deployment") @("CI/CD PIPELINE","A/B TESTING") @()
New-Zettel "BLUE GREEN" "# BLUE GREEN #devops #deployment #zero-downtime #уровень1" "Деплой с двумя окружениями для нулевого даунтайма." @("DevOps","Deployment") @("CI/CD PIPELINE","CANARY RELEASE") @()
New-Zettel "CANARY RELEASE" "# CANARY RELEASE #devops #deployment #testing #уровень1" "Постепенный релиз для части пользователей." @("DevOps","Deployment") @("BLUE GREEN","FEATURE FLAGS") @()
New-Zettel "SONARQUBE" "# SONARQUBE #quality #code-analysis #static #уровень1" "Статический анализ кода для поиска багов и уязвимостей." @("Quality","Analysis") @("CODE REVIEW","CI/CD PIPELINE") @()
New-Zettel "WEBPACK" "# WEBPACK #bundler #frontend #build #уровень1" "Сборщик модулей для JavaScript приложений." @("Build Tools","Frontend") @("VITE","ROLLUP") @()
New-Zettel "VITE BUNDLER" "# VITE BUNDLER #bundler #dev-server #frontend #уровень1" "Быстрый сборщик с HMR через ESM модули." @("Build Tools","Frontend") @("WEBPACK","ROLLUP") @()
New-Zettel "JEST" "# JEST #testing #javascript #framework #уровень1" "Фреймворк тестирования с нулевой конфигурацией." @("Testing","JavaScript") @("UNIT TESTING","MOCK") @()

Write-Host "Создано заметок: $(@(Get-ChildItem -LiteralPath $outputDir -Filter '*.md' -File | Where-Object { $_.Name -ne 'Task.md' -and $_.Name -ne 'gen.ps1' }).Count)"
