# Knowledge Galaxy Generator - Python version
# Creates 2000 notes with 15000+ links

import os
import random

random.seed(12345)

base_dir = r"C:\obsidian\Main\KnowledgeGalaxy"

# Create cluster directories
clusters = ["Psychology", "Philosophy", "GameTheory", "Economics", "AI", "Programming", "Learning", "Productivity"]
for c in clusters:
    os.makedirs(os.path.join(base_dir, c), exist_ok=True)

# ============ CLUSTER CONTENT ============
print("Defining cluster content...")

cluster_content = {
    "Psychology": {
        "Cognitive Psychology": ["Perception", "Attention", "Memory", "Thinking", "Language", "Imagination", "Sensation", "Conceptual Thinking", "Abstract Thinking", "Critical Thinking", "Creative Thinking", "Convergent Thinking", "Divergent Thinking", "Metacognition", "Cognitive Processes", "Cognitive Schemas", "Cognitive Biases", "Mental Models", "Problem Solving", "Decision Making", "Cognitive Load", "Working Memory", "Long-term Memory", "Episodic Memory", "Semantic Memory", "Procedural Memory", "Prospective Memory", "Concentration", "Distraction", "Focus", "Selective Attention", "Sustained Attention", "Divided Attention", "Attention Switching", "Visual Perception", "Auditory Perception", "Proprioception", "Interoception", "Neuroplasticity", "Neuroscience", "Cognitive Psychology", "Experimental Psychology", "Psychophysics", "Biopsychology", "Neurobiology", "Cortical Processes", "Subcortical Processes", "Limbic System", "Neocortex", "Prefrontal Cortex", "Hippocampus", "Cerebellum", "Brain Stem", "Amygdala", "Hypothalamus"],
        "Social Psychology": ["Social Perception", "Social Cognition", "Stereotypes", "Prejudice", "Discrimination", "Conformity", "Obedience", "Influence", "Persuasion", "Social Influence", "Group Pressure", "Group Polarization", "Social Facilitation", "Social Loafing", "Diffusion of Responsibility", "Bystander Effect", "Inter-group Conflict", "Social Identity", "Self-categorization", "Social Comparison", "Attribution", "Fundamental Attribution Error", "Egocentric Attribution", "Correspondent Inference", "Effort Justification", "Cognitive Dissonance", "Social Learning", "Behavioral Modeling", "Imitation", "Altruism", "Egoism", "Cooperation", "Competition", "Social Support", "Emotional Support", "Informational Support", "Social Isolation", "Loneliness", "Communication", "Nonverbal Communication", "Body Language", "Microexpressions", "Emotional Intelligence", "Social Intelligence", "Social Competence", "Assertiveness"],
        "Developmental Psychology": ["Child Psychology", "Developmental Psychology", "Cognitive Development", "Emotional Development", "Social Development", "Language Development", "Psychosocial Development", "Developmental Stages", "Developmental Crises", "Self-concept", "Self-esteem", "Self-knowledge", "Self-regulation", "Self-efficacy", "Autonomy", "Dependence", "Attachment", "Attachment Types", "Secure Attachment", "Anxious Attachment", "Avoidant Attachment", "Disorganized Attachment", "Identity", "Identity Search", "Identity Crisis", "Eriksonian Stages", "Piagetian Stages", "Kohlbergian Stages", "Moral Development", "Empathy", "Guilt", "Shame", "Competence", "Intrinsic Motivation", "Extrinsic Motivation", "Needs", "Hierarchy of Needs", "Maslow", "Self-actualization", "Creativity", "Giftedness", "Intelligence", "IQ", "EQ", "Adaptation", "Coping", "Resilience"],
        "Personality Psychology": ["Personality Psychology", "Personality Theories", "Personality Traits", "Big Five", "MBTI", "Temperament", "Sanguine", "Choleric", "Melancholic", "Phlegmatic", "Character", "Dispositions", "Psychoanalytic Theory", "Freud", "Jung", "Adler", "Erikson", "Behaviorism", "Skinner", "Pavlov", "Tolman", "Cognitive Psychology", "Humanistic Psychology", "Rogers", "Maslow", "Existential Psychology", "Positive Psychology", "Happiness", "Well-being", "Flourishing", "Self-realization", "Meaning of Life", "Values", "Beliefs", "Attitude", "Interests", "Abilities", "Talents", "Intelligence", "Emotions", "Feelings", "Mood", "Affect", "Passion", "Drive", "Motivation", "Determination", "Persistence", "Stubbornness", "Flexibility", "Adaptability", "Openness", "Conscientiousness", "Extraversion", "Aggression"],
        "Clinical Psychology": ["Clinical Psychology", "Mental Disorders", "Depression", "Anxiety Disorder", "Panic Disorder", "Phobias", "OCD", "PTSD", "Bipolar Disorder", "Schizophrenia", "Personality Disorders", "Borderline Personality Disorder", "Narcissistic Personality Disorder", "Antisocial Personality Disorder", "Avoidant Personality Disorder", "Dependent Personality Disorder", "Psychotherapy", "Cognitive-Behavioral Therapy", "Psychoanalysis", "Gestalt Therapy", "Family Therapy", "Group Therapy", "Art Therapy", "Body Therapy", "Music Therapy", "Psychodynamic Therapy", "Person-centered Therapy", "Desensitization", "Exposure Therapy", "Rational Emotive Therapy", "Psychopharmacology", "Antidepressants", "Anxiolytics", "Neuroleptics", "Mood Stabilizers", "Psychostimulants", "Nootropics", "Diagnosis", "Psychodiagnostics", "Psychological Counseling"],
        "Emotional Psychology": ["Emotions", "Emotion Theories", "Basic Emotions", "Complex Emotions", "Joy", "Sadness", "Anger", "Fear", "Surprise", "Disgust", "Contempt", "Pride", "Shame", "Guilt", "Envy", "Jealousy", "Gratitude", "Love", "Hatred", "Hope", "Despair", "Anxiety", "Stress", "Burnout", "Emotional Burnout", "Emotion Regulation", "Emotion Suppression", "Cognitive Appraisal", "Emotional Intelligence", "Emotional Competence", "Mood", "Affect", "Passion", "Sensitivity", "Emotional Stability", "Emotional Lability", "Alexithymia", "Emotional Reactivity", "Emotional Responsiveness", "Empathy", "Compassion", "Altruism"],
        "Motivation & Behavior": ["Motivation", "Motivation Theories", "Intrinsic Motivation", "Extrinsic Motivation", "Drives", "Urges", "Needs", "Hierarchy of Needs", "Expectancy Theory", "Equity Theory", "Self-determination Theory", "Goal Theory", "Reward", "Punishment", "Reinforcement", "Positive Reinforcement", "Negative Reinforcement", "Extinction", "Behavior Shaping", "Self-control", "Procrastination", "Self-motivation", "Self-efficacy", "Optimism", "Pessimism", "Locus of Control", "Subjective Control", "Self-esteem", "Narcissism", "Self-respect", "Self-acceptance", "Determination", "Persistence", "Readiness for Action", "Decisiveness", "Impulsivity", "Self-regulation"]
    },
    "Philosophy": {
        "Metaphysics": ["Metaphysics", "Ontology", "Substance", "Attribute", "Mode", "Essence", "Existence", "Being", "Nothing", "Becoming", "Cause", "Effect", "Determinism", "Indeterminism", "Free Will", "Necessity", "Contingency", "Possibility", "Actuality", "Potentiality", "Form", "Matter", "Motion", "Time", "Space", "Cosmos", "Order", "Chaos", "One", "Multiplicity", "Identity", "Difference", "Contradiction", "Whole", "Part", "Structure", "Function", "System", "Element", "Connection", "Relation", "Reality", "Illusion", "Truth", "Falsehood", "Error", "Knowledge", "Wisdom"],
        "Epistemology": ["Epistemology", "Theory of Knowledge", "Knowledge", "Opinion", "Belief", "Justified Belief", "Truth", "Correspondence Theory", "Coherence Theory", "Pragmatic Theory", "Rationalism", "Empiricism", "Criticism", "Skepticism", "Agnosticism", "Dogmatism", "Relativism", "Objectivity", "Subjectivity", "Intersubjectivity", "Transcendentality", "A Priori", "A Posteriori", "Analytic", "Synthetic", "Logic", "Dialectics", "Hermeneutics", "Phenomenology", "Deduction", "Induction", "Abduction", "Analogy", "Thought Experiment", "Falsification", "Verification", "Paradigm", "Scientific Revolution", "Fallibilism", "Criterion of Truth", "Gnoseology", "Methodology"],
        "Ethics": ["Ethics", "Morality", "Good", "Evil", "Justice", "Duty", "Responsibility", "Freedom", "Autonomy", "Dignity", "Respect", "Benefit", "Happiness", "Eudaimonia", "Utilitarianism", "Consequentialism", "Deontology", "Virtue Ethics", "Cardiology", "Virtue", "Vice", "Wisdom", "Courage", "Moderation", "Justice", "Honesty", "Kindness", "Generosity", "Compassion", "Forgiveness", "Gratitude", "Humility", "Diligence", "Loyalty", "Reliability", "Sincerity", "Patience", "Principle", "Rule", "Norm", "Law", "Imperative", "Categorical Imperative", "Golden Rule", "Principle of Utility", "Principle of Justice", "Principle of Autonomy", "Principle of Non-violence", "Bioethics", "Business Ethics", "Technology Ethics", "AI Ethics", "Global Ethics", "Environmental Ethics", "Labor Ethics", "Social Ethics", "Political Ethics", "Military Ethics"],
        "Political Philosophy": ["Political Philosophy", "State", "Power", "Sovereignty", "Democracy", "Authoritarianism", "Totalitarianism", "Liberalism", "Conservatism", "Socialism", "Communism", "Anarchism", "Republic", "Monarchy", "Oligarchy", "Timocracy", "Political Contract", "Social Contract", "Human Rights", "Civil Rights", "Political Rights", "Social Rights", "Equality", "Freedom", "Brotherhood", "Solidarity", "Nationalism", "Cosmopolitanism", "Globalism", "Localization", "Sovereignty", "Intervention", "Non-intervention", "Humanitarian Intervention", "Peacekeeping", "Collective Security", "Disarmament", "Nuclear Deterrence", "Geopolitics", "Political Realism"],
        "Aesthetics": ["Aesthetics", "Beauty", "Beautiful", "Sublime", "Tragic", "Comic", "Grotesque", "Irony", "Humor", "Art", "Creativity", "Genius", "Talent", "Inspiration", "Aesthetic Taste", "Aesthetic Judgment", "Aesthetic Experience", "Beauty of Nature", "Beauty of Art", "Formalism", "Content", "Form", "Style", "Genre", "Symbol", "Allegory", "Metaphor", "Archetype"],
        "Existentialism & Phenomenology": ["Existentialism", "Existence", "Being-toward-death", "Being-in-the-world", "Absurd", "Anxiety", "Fear", "Despair", "Choice", "Responsibility", "Authenticity", "Inauthenticity", "Facticity", "Transcendence", "Immanence", "Phenomenology", "Intentionality", "Lifeworld", "Horizon", "Temporality", "Subject", "Object", "Other", "Others", "Dialogue", "Heidegger", "Sartre", "Camus", "Buber"],
        "Logic": ["Logic", "Formal Logic", "Mathematical Logic", "Symbolic Logic", "Propositional Logic", "Predicate Logic", "Modal Logic", "Dialectical Logic", "Inductive Logic", "Abductive Logic", "Paradox", "Antinomy", "Contradiction", "Consistency", "Validity", "Soundness", "Entailment", "Implication", "Conjunction", "Disjunction"]
    },
    "GameTheory": {
        "Core Concepts": ["Game Theory", "Game", "Player", "Strategy", "Strategy Set", "Payoff", "Loss", "Payoff Function", "Profit", "Nash Equilibrium", "Strategic Equilibrium", "Optimality", "Dominant Strategy", "Strategic Dominance", "Mixed Strategy", "Pure Strategy", "Probability Distribution", "Information", "Complete Information", "Incomplete Information", "Perfect Information", "Imperfect Information", "Cooperative Games", "Non-cooperative Games", "Coordination Games", "Competitive Games", "Zero-sum Games", "Positive-sum Games", "Negative-sum Games", "Two-sided Games", "Multi-sided Games", "Symmetric Games", "Asymmetric Games", "One-shot Games", "Repeated Games", "Survival Games", "Bayesian Games", "Dynamic Games", "Stochastic Games"],
        "Classic Games": ["Prisoner's Dilemma", "Stag Hunt", "Hawk-Dove", "Battle of the Sexes", "Matching Pennies", "Rock Paper Scissors", "Centipede Game", "Ultimatum Game", "Dictator Game", "Trust Game", "Public Goods Game", "War of Attrition", "Colonel Blotto", "Keynesian Beauty Contest", "El Farol Bar", "Nash Bargaining", "Bertrand Competition", "Cournot Competition", "Stackelberg Leadership", "Hotelling Location", "Auction Theory", "First-price Auction", "Second-price Auction", "English Auction", "Dutch Auction", "Sealed-bid Auction"],
        "Applications": ["Applications of Game Theory", "In Negotiations", "In Business", "In Politics", "In Military", "In Economics", "In Ecology", "In Sociology", "In Evolution", "In Genetics", "In Neuroscience", "In Computer Games", "In Sports", "In Chess", "In Poker", "In Bridge", "Pricing", "Market Strategy", "Competition", "Monopoly", "Oligopoly", "Monopsony", "Antitrust Policy", "Regulation", "Deregulation", "Privatization", "Nationalization", "Trade Negotiations", "Diplomacy", "Sanctions", "Embargo", "War", "Peacekeeping", "Nuclear Deterrence", "Arms Race", "Environmental Agreements", "Climate Negotiations"],
        "Mechanism Design": ["Mechanism Design", "Mechanism", "Institution", "Rules", "Procedure", "Auction", "Tender", "Routing", "Distribution", "Allocation", "Vickrey Mechanism", "Clarke Mechanism", "Groves-Ledyard", "Implementability", "Individual Rationality", "Budget Balance", "Strategic Stability", "Gale-Shapley", "Shapley Value", "Pareto Efficiency", "Sufficient Complexity", "Mechanism Design Theory", "Revelation Principle", "Incentive Compatibility", "Participation Constraint", "Truthfulness", "Strategy-proofness", "Ex-post Incentive Compatibility"],
        "Evolutionary Game Theory": ["Evolutionary Game Theory", "Evolutionarily Stable Strategy", "ESS", "Natural Selection", "Sociobiology", "Behavioral Ecology", "Kin Altruism", "Reciprocal Altruism", "Cooperation", "Trust", "Reputation", "Punishment", "Retaliation", "Forgiveness", "Signaling", "Honesty", "Deception", "Mimicry", "Coevolution", "Red Queen", "Arms Race", "Symmetric Strategies", "Asymmetric Strategies", "Hawk Strategy", "Dove Strategy", "Tit-for-tat", "Grim Trigger", "Generous Tit-for-tat", "Random Strategy"],
        "Decision Theory": ["Decision Theory", "Choice Theory", "Rational Choice", "Preferences", "Preference Order", "Probability", "Subjective Probability", "Expected Utility", "Expected Utility Theory", "Ellsberg Paradox", "Allais Paradox", "Prospect Theory", "Utility", "Antipathy to Loss", "Framing Effect", "Anchoring Effect", "Hyperbolic Discounting"]
    },
    "Economics": {
        "Microeconomics": ["Microeconomics", "Demand", "Supply", "Equilibrium", "Price", "Elasticity", "Price Elasticity", "Supply Elasticity", "Consumer", "Producer", "Firm", "Market", "Competition", "Monopoly", "Oligopoly", "Monopsony", "Monopolistic Competition", "Production Function", "Costs", "Fixed Costs", "Variable Costs", "Marginal Costs", "Average Costs", "Total Costs", "Profit", "Loss", "Profit Maximization", "Cost Minimization", "Economies of Scale", "Differentiation", "Integration", "Vertical Integration", "Horizontal Integration", "Pricing", "Price Discrimination", "Pareto Efficiency", "Externality", "Positive Externalities", "Negative Externalities", "Public Goods", "Pure Public Goods", "Mixed Goods", "Information Asymmetry", "Adverse Selection", "Moral Hazard", "Principal-Agent", "Signaling", "Screening", "Labor Market", "Wage", "Professions", "Minimum Wage", "Unemployment"],
        "Macroeconomics": ["Macroeconomics", "GDP", "National Income", "GNP", "NNP", "Inflation", "Deflation", "Stagnation", "Stagflation", "Hyperinflation", "Unemployment", "Frictional Unemployment", "Structural Unemployment", "Cyclical Unemployment", "Natural Unemployment", "Fiscal Policy", "Monetary Policy", "Interest Rate", "Money Supply", "Credit", "Banking System", "Central Bank", "Federal Reserve", "European Central Bank", "Bank of Russia", "Interbank Market", "Bond Market", "Stock Market", "Foreign Exchange Market", "Exchange Rate", "Fixed Exchange Rate", "Floating Exchange Rate", "Budget", "Budget Deficit", "Budget Surplus", "National Debt", "Trade Balance", "Export", "Import", "Balance of Payments", "Capital Flow", "Foreign Investment", "FDI", "Portfolio Investment", "Economic Growth", "Potential GDP", "Recession", "Depression", "Business Cycle"],
        "Financial Economics": ["Financial Economics", "Finance", "Money", "Capital", "Investment", "Investment Portfolio", "Diversification", "Risk", "Return", "Liquidity", "Volatility", "Capital Market", "Debt Market", "Stock Market", "Bonds", "Stocks", "Dividends", "Coupon", "Exchange", "Stock Exchange", "Trading Platform", "Broker", "Dealer", "Market Maker", "Spread", "Options", "Futures", "Swaps", "Derivatives", "Hedging", "Speculation", "Arbitrage", "Margin Trading", "Leverage", "Bankruptcy", "Liquidation", "Restructuring", "Mergers and Acquisitions", "IPO", "Venture Capital", "Private Equity", "Hedge Funds", "Index Funds", "ETF", "Mutual Funds", "Cryptocurrencies", "Bitcoin", "Blockchain", "DeFi"],
        "International Economics": ["International Economics", "International Trade", "Trade Policy", "Customs Union", "Free Trade Zone", "Tariffs", "Quotas", "Subsidies", "Anti-subsidy Duties", "Anti-dumping Duties", "WTO", "IMF", "World Bank", "International Organizations", "Globalization", "Deglobalization", "Regionalization", "Localization", "International Finance", "Currency Markets", "International Capital Flows", "Capital Flight", "Currency Crises", "Debt Crises", "International Migration", "Refugee Economics", "Labor Migration", "Brain Drain", "International Investment", "Multinational Corporations", "Global Value Chains", "Digital Economy", "E-commerce", "International Development", "Development Economics", "Poverty Reduction", "Microfinance", "Inclusive Finance", "Sustainable Development", "ESG", "Corporate Social Responsibility"],
        "Behavioral Economics": ["Behavioral Economics", "Cognitive Biases", "Hyperbolic Discounting", "Anchoring Effect", "Reinforcement Effect", "Scale Effect", "Order Effect", "Primacy Effect", "Recency Effect", "Novelty Effect", "Familiarity Effect", "Nominal Effect", "Charity Effect", "Involvement Effect", "Endowment Effect", "Scarcity Effect", "Contrast Effect", "Framing Effect", "Expectation Effect", "Positioning Effect", "Social Proof Effect", "Authority Effect", "Reciprocity Effect", "Scarcity Effect", "Fear Effect", "Greed Effect", "Belonging Effect", "Status Effect", "Nudge", "Choice Architecture", "Default Design", "Simplification", "Social Norms", "Automatic Enrollment", "Choice Programming"],
        "Institutional Economics": ["Institutional Economics", "Institutions", "Institutional Environment", "Formal Institutions", "Informal Institutions", "Property Rights", "Contracts", "Transaction Costs", "Hierarchy", "Market", "Mixed Economy", "Public Sector", "Private Sector", "Civil Society", "Corporate Governance", "Stakeholders", "Shareholders", "Directors", "Management", "Regulation"]
    },
    "AI": {
        "Machine Learning": ["Machine Learning", "Supervised Learning", "Unsupervised Learning", "Reinforcement Learning", "Classification", "Regression", "Clustering", "Anomaly Detection", "Recommendation Systems", "Generative Models", "Discriminative Models", "Linear Regression", "Logistic Regression", "Decision Trees", "Random Forest", "Gradient Boosting", "XGBoost", "LightGBM", "Support Vector Machines", "SVM", "K-Nearest Neighbors", "KNN", "Naive Bayes", "Bayesian Networks", "Neural Networks", "Artificial Neural Networks", "Perceptron", "Multilayer Perceptron", "CNN", "Convolutional Neural Networks", "RNN", "Recurrent Neural Networks", "LSTM", "GRU", "Transformers", "Attention Mechanism", "Self-attention", "BERT", "GPT", "T5", "LLM", "Large Language Models", "GAN", "Generative Adversarial Networks", "VAE", "Variational Autoencoders", "Autoencoder", "Representation Learning", "Feature Engineering", "Transfer Learning"],
        "Deep Learning": ["Deep Learning", "Deep Neural Networks", "Neural Architecture", "Activation Functions", "ReLU", "Sigmoid", "Tanh", "Softmax", "Loss Function", "Cross-entropy", "MSE", "MAE", "Optimizers", "SGD", "Adam", "RMSprop", "AdaGrad", "Regularization", "Dropout", "Batch Normalization", "Layer Normalization", "Data Augmentation", "Model Training", "Epoch", "Batch", "Learning Rate", "Gradient Descent", "Backpropagation", "Weights", "Biases", "Model Parameters", "Hyperparameters", "Validation", "Cross-validation", "Overfitting", "Underfitting", "Bias-Variance Tradeoff", "Ensemble Methods", "Bagging", "Boosting", "Stacking"],
        "NLP": ["Natural Language Processing", "NLP", "Tokenization", "Stemming", "Lemmatization", "POS Tagging", "Named Entity Recognition", "NER", "Entity Extraction", "Sentiment Analysis", "Text Classification", "Machine Translation", "Neural Machine Translation", "Sequence-to-sequence", "Attention", "Transformer", "BERT", "GPT", "T5", "Dialogue Systems", "Chatbots", "Question Answering", "Text Summarization", "Information Extraction", "Knowledge Graphs", "Word Embeddings", "Word2Vec", "GloVe", "FastText", "Contextual Embeddings", "ELMo", "Prompt Engineering", "In-context Learning", "Few-shot Learning", "Zero-shot Learning", "Chain-of-thought", "ReAct"],
        "Computer Vision": ["Computer Vision", "Image Processing", "Object Detection", "Semantic Segmentation", "Instance Segmentation", "Panoptic Segmentation", "Face Recognition", "Face Detection", "OCR", "Document Analysis", "Video Content", "Video Analysis", "Image Generation", "Style Transfer", "Super-resolution", "Depth Estimation", "Optical Flow", "3D Reconstruction", "NeRF", "Point Clouds", "LiDAR", "Stereo Vision", "Epipolar Geometry", "Camera Calibration", "Projective Geometry", "Camera Matrix"],
        "Reinforcement Learning": ["Reinforcement Learning", "Agent", "Environment", "State", "Action", "Reward", "Policy", "Value Function", "Q-Learning", "SARSA", "Deep Q-Network", "DQN", "Policy Gradients", "REINFORCE", "Actor-Critic", "A3C", "PPO", "TRPO", "SAC", "TD3", "Model-based RL", "Model-free RL", "Exploration vs Exploitation", "Epsilon-greedy", "UCB", "Thompson Sampling", "Multi-armed Bandit", "Inverse RL", "Imitation Learning", "Reward Shaping"],
        "AI Ethics & Safety": ["AI Ethics", "AI Safety", "Alignment", "AI Alignment", "Control Problem", "Superintelligence", "Technological Singularity", "Transhumanism", "Posthumanism", "AI Rights", "Artificial Consciousness", "Philosophy of AI", "Ethical Algorithms", "Fairness in AI", "Explainable AI", "XAI", "Transparency", "Accountability", "Bias in Data", "Bias in Models", "Long-term Risks", "Existential Risk"],
        "AI Applications": ["AI Applications", "Autonomous Vehicles", "Self-driving Cars", "Robotics", "Medical Diagnosis", "Medical AI", "Financial Analysis", "Algorithmic Trading", "Fraud Detection", "Personalization", "Recommendation Systems", "Generative AI", "Content Creation", "Automation", "RPA", "Virtual Assistants", "Chatbots", "Voice Assistants", "Machine Translation", "Educational AI"]
    },
    "Programming": {
        "Programming Languages": ["Programming", "Programming Languages", "Programming Paradigms", "Imperative Programming", "Declarative Programming", "Procedural Programming", "Structured Programming", "Object-Oriented Programming", "OOP", "Functional Programming", "Logic Programming", "Metaprogramming", "Python", "JavaScript", "TypeScript", "Java", "C", "C++", "C#", "Go", "Rust", "Kotlin", "Swift", "Ruby", "PHP", "Perl", "R", "Julia", "Scala", "Haskell", "Erlang", "Elixir", "Clojure", "Lisp", "Scheme", "Prolog", "SQL", "HTML", "CSS", "Bash", "PowerShell", "Assembly", "Fortran", "COBOL", "Pascal", "Delphi", "Objective-C", "Dart", "Lua"],
        "Algorithms & Data Structures": ["Algorithms", "Data Structures", "Sorting", "Quick Sort", "Merge Sort", "Insertion Sort", "Selection Sort", "Bubble Sort", "Heap Sort", "Counting Sort", "Radix Sort", "Search", "Linear Search", "Binary Search", "DFS", "BFS", "A*", "Dijkstra", "Bellman-Ford", "Floyd-Warshall", "Kruskal", "Prim", "Boruvka", "Graphs", "Trees", "Binary Tree", "BST", "AVL Tree", "Red-Black Tree", "B-Tree", "B+ Tree", "Hash Tables", "Hash Array", "Collisions", "Open Hashing", "Closed Hashing", "Stack", "Queue", "Deque", "Priority Queue", "Linked List", "Doubly Linked List", "Circular List", "Array", "Dynamic Array", "Vector", "String", "Dynamic Programming", "Greedy Algorithms", "Divide and Conquer", "Backtracking", "Brute Force", "Memoization", "Tabulation", "Amortized Analysis"],
        "Software Architecture": ["Software Architecture", "Design Patterns", "Creational Patterns", "Structural Patterns", "Behavioral Patterns", "Singleton", "Factory", "Abstract Factory", "Builder", "Prototype", "Adapter", "Bridge", "Composite", "Decorator", "Facade", "Flyweight", "Proxy", "Chain of Responsibility", "Command", "Iterator", "Mediator", "Memento", "Observer", "State", "Strategy", "Template Method", "Visitor", "Interpreter", "Microservices Architecture", "Monolithic Architecture", "Service-Oriented Architecture", "SOA", "Event-driven Architecture", "CQRS", "Event Sourcing", "DDD", "Domain-Driven Design", "Hexagonal Architecture", "Clean Architecture", "Serverless", "Containerization", "Docker", "Kubernetes", "CI/CD", "DevOps", "MLOps"],
        "Web Development": ["Web Development", "Frontend", "Backend", "Fullstack", "HTML5", "CSS3", "JavaScript", "TypeScript", "React", "Vue.js", "Angular", "Svelte", "Next.js", "Nuxt.js", "REST API", "GraphQL", "gRPC", "WebSocket", "Node.js", "Express.js", "Fastify", "NestJS", "Django", "Flask", "FastAPI", "Spring Boot", "Laravel", "PostgreSQL", "MySQL", "MongoDB", "Redis", "Elasticsearch", "AWS", "Azure", "Google Cloud", "Vercel", "Netlify"],
        "DevOps & Infrastructure": ["DevOps", "Infrastructure", "Cloud Computing", "AWS", "Azure", "Google Cloud Platform", "Docker", "Kubernetes", "Terraform", "Ansible", "Puppet", "Chef", "Jenkins", "GitLab CI", "GitHub Actions", "CircleCI", "Monitoring", "Prometheus", "Grafana", "ELK Stack", "Logging", "Tracing", "Metrics", "Alerting", "Scaling", "Horizontal Scaling", "Vertical Scaling", "Load Balancing", "CDN", "Microservices", "Service Mesh", "API Gateway", "Secrets Management", "HashiCorp Vault"],
        "Data Science": ["Data Science", "Data Analysis", "Data Visualization", "Pandas", "NumPy", "SciPy", "Matplotlib", "Seaborn", "Plotly", "Jupyter", "RStudio", "Data Wrangling", "Data Cleaning", "Feature Engineering", "Statistical Analysis", "A/B Testing", "Hypothesis Testing", "Regression", "Classification", "Clustering", "Dimensionality Reduction", "PCA", "t-SNE", "UMAP", "Data Pipelines", "ETL", "Apache Spark", "Hadoop", "Kafka", "Airflow", "Data Lake", "Data Warehouse", "Data Mart", "Business Intelligence", "BI", "Dashboard"],
        "Cybersecurity": ["Cybersecurity", "Information Security", "Network Security", "Application Security", "Data Security", "Cryptography", "Encryption", "Asymmetric Encryption", "Symmetric Encryption", "Hashing", "Digital Signatures", "PKI", "SSL/TLS", "Web Application Security", "OWASP Top 10", "SQL Injection", "XSS", "CSRF", "Brute Force", "DDoS Attacks", "Penetration Testing", "Bug Bounty", "Vulnerabilities", "Exploits", "Malware", "Viruses", "Trojans", "Ransomware", "Spyware", "Phishing", "Social Engineering", "Multi-factor Authentication", "RBAC", "Zero Trust", "Security Audit", "Compliance", "GDPR", "PCI DSS", "ISO 27001"]
    },
    "Learning": {
        "Learning Theory": ["Learning", "Learning Theories", "Behavioral Theories", "Cognitive Theories", "Constructivism", "Connectivism", "Experiential Learning", "Collective Learning", "Social Learning", "Distance Learning", "Didactics", "Pedagogy", "Andragogy", "Knowledge", "Skills", "Competence", "Qualification", "Learning Levels", "Bloom's Taxonomy", "Critical Thinking", "Creative Thinking", "Productive Thinking", "Reproductive Thinking", "Analytical Thinking", "Synthetic Thinking", "Motivation to Learn", "Intrinsic Motivation", "Extrinsic Motivation", "Self-efficacy", "Self-regulation", "Learning Autonomy", "Feedback", "Assessment", "Self-assessment", "Formative Assessment", "Summative Assessment", "Diagnostic Assessment"],
        "Memory & Cognition": ["Memory", "Memory Theories", "Short-term Memory", "Long-term Memory", "Working Memory", "Episodic Memory", "Semantic Memory", "Procedural Memory", "Declarative Memory", "Encoding", "Storage", "Retrieval", "Forgetting", "Ebbinghaus Forgetting Curve", "Spaced Repetition", "Serial Position Effect", "Primacy Effect", "Recency Effect", "Clustering", "Associative Learning", "Mnemonics", "Rehearsal", "Decomposition", "Abstraction", "Generalization", "Specification", "Induction", "Deduction", "Analogy", "Thought Experiment", "Cognitive Strategies", "Deep Processing Strategy", "Shallow Processing Strategy", "Organization Strategy", "Comprehension Strategy", "Memory Strategy", "Metacognition", "Self-awareness"],
        "Educational Technologies": ["Educational Technologies", "EdTech", "E-Learning", "Mobile Learning", "m-Learning", "Gamification", "Game-based Learning", "Virtual Reality in Education", "VR in Education", "Augmented Reality in Education", "AR in Education", "Online Courses", "MOOC", "Blended Learning", "Flipped Classroom", "Workshops", "Seminars", "Lectures", "Practicums", "Laboratory Work", "Internships", "Mentoring", "Tutoring", "Facilitation", "Self-directed Learning", "Autonomous Learning", "Lifelong Learning", "Continuous Learning", "Formal Learning", "Informal Learning", "Non-formal Learning", "Curricula", "Syllabi", "Learning Materials"],
        "Neuroscience of Learning": ["Neuroscience of Learning", "Neuroplasticity", "Synaptic Plasticity", "Long-term Potentiation", "LTP", "Long-term Depression", "LTD", "Neurogenesis", "Myelination", "Cortical Organization", "Lateralization", "Corpus Callosum", "Visual Cortex", "Auditory Cortex", "Motor Cortex", "Sensory Cortex", "Prefrontal Cortex", "Hippocampus", "Amygdala", "Cerebellum", "Basal Ganglia", "Thalamus", "Hypothalamus", "Neurotransmitters", "Dopamine", "Serotonin", "Norepinephrine", "Acetylcholine", "GABA", "Glutamate", "Endorphins", "Neurocognitive Processes", "Attention", "Perception", "Memory", "Language", "Thinking", "Planning", "Decision Making", "Cognitive Control", "Executive Functions", "Stress and Learning", "Sleep and Learning", "Physical Activity", "Nutrition and Brain", "Brain Aging", "Neurodegenerative Diseases"]
    },
    "Productivity": {
        "Time Management": ["Productivity", "Time Management", "Planning", "Strategic Planning", "Tactical Planning", "Operational Planning", "Goal Decomposition", "Task Decomposition", "Ivy Lee Method", "Pomodoro Technique", "Time Blocking", "Time Batching", "Deep Work", "Shallow Work", "Calendar", "Planner", "TODO List", "Priorities", "Eisenhower Matrix", "80/20 Rule", "Pareto Principle", "Important vs Urgent", "Deadline", "Procrastination", "Self-discipline", "Self-control", "Self-motivation", "Self-efficacy", "Habits", "Habit Formation", "Habit Breaking", "Habit Stacking", "Routines", "Micro-habits"],
        "Productivity Systems": ["Productivity Systems", "Getting Things Done", "GTD", "David Allen Method", "Zettelkasten System", "Cornell System", "PARA System", "Tiago Forte Method", "Building a Second Brain", "Knowledge Base", "Second Brain", "Inbox", "Processing", "Organization", "Storage", "Retrieval", "Archiving", "Reflection", "Weekly Review", "Monthly Review", "Annual Review", "Goal Setting", "OKR", "KPI", "SMART Goals", "Roadmap", "Backlog", "Sprint", "Kanban", "Scrum", "Personal Kanban", "Three-Bin System", "ABCDE System"],
        "Focus & Attention": ["Focus", "Concentration", "Attention", "Deep Focus", "Distraction", "Multitasking", "Task Switching", "Context Switching", "Switching Cost", "Focus Recovery", "Workspace", "Office", "Home Office", "Coworking", "Caffeine", "Nootropics", "Meditation", "Mindfulness", "Breathing Practices", "Walking", "Physical Activity", "Sleep", "Sleep Hygiene", "Sleep Schedule", "Chronotype", "Morning Type", "Evening Type", "Circadian Rhythms", "Energy", "Energy Level", "Peak Energy", "Energy Dip", "Energy Recovery", "Micro-breaks", "20-20-20 Technique", "Ergonomics", "Workplace", "Space Organization", "Minimalism", "Digital Minimalism"],
        "Decision Making & Thinking": ["Decision Making", "Thinking Processes", "Critical Thinking", "Systematic Thinking", "Heuristics", "Availability Heuristic", "Representativeness Heuristic", "Anchoring Heuristic", "Bandwagon Effect", "Cognitive Biases", "Confirmation Bias", "Dunning-Kruger Effect", "Fundamental Attribution Error", "Bystander Effect", "Mental Models", "First Principles", "Inversion", "Second-order Effects", "Thought Experiments", "Alternative Hypotheses", "Fork", "Dilemmas", "Paradoxes", "Analysis of Decisions", "Decision Matrix", "Decision Tree", "SWOT Analysis", "PEST Analysis", "Force Field Analysis", "Risk Assessment", "Risk Management", "Pre-mortem", "Post-mortem", "Action Review"],
        "Personal Development": ["Personal Development", "Self-development", "Self-knowledge", "Self-actualization", "Growth", "Transformation", "Change", "Growth Mindset", "Fixed Mindset", "Resilience", "Stress Resistance", "Emotional Intelligence", "Self-awareness", "Self-regulation", "Motivation", "Empathy", "Social Skills", "Communication", "Public Speaking", "Presentations", "Networking", "Business Communication", "Leadership Skills", "Leadership", "Management", "Delegation", "Team Motivation", "Feedback", "Mentoring", "Career Growth", "Career Planning", "Resume", "Interview", "Personal Brand", "Work-life Balance", "Burnout", "Burnout Prevention", "Recovery", "Harmony", "Integrity", "Authenticity", "Meaningfulness"]
    }
}

# ============ BRIDGE CONNECTIONS ============
bridge_connections = {
    "Psychology": ["Philosophy", "Learning", "Productivity"],
    "Philosophy": ["Psychology", "GameTheory", "AI"],
    "GameTheory": ["Philosophy", "Economics", "AI"],
    "Economics": ["GameTheory", "Programming", "Productivity"],
    "AI": ["Programming", "Philosophy", "Learning"],
    "Programming": ["AI", "Economics", "Productivity"],
    "Learning": ["Psychology", "AI", "Productivity"],
    "Productivity": ["Psychology", "Learning", "Programming"]
}

# ============ GENERATE FILES ============
print("\n=== Generating Files ===")

all_cluster_notes = {}
total_links = 0

for cluster, topics in cluster_content.items():
    print(f"\nProcessing {cluster}...")
    cluster_dir = os.path.join(base_dir, cluster)
    
    all_notes_in_cluster = []
    for category, notes in topics.items():
        all_notes_in_cluster.extend(notes)
    all_cluster_notes[cluster] = all_notes_in_cluster
    
    # Get other cluster notes for bridges
    other_notes = []
    for other_cluster, other_topics in cluster_content.items():
        if other_cluster != cluster:
            for category, notes in other_topics.items():
                other_notes.extend(notes)
    
    for note in all_notes_in_cluster:
        safe_name = note.replace("/", "_").replace("\\", "_").replace("*", "Star").replace("?", "").replace(":", "").replace("<", "").replace(">", "").replace("|", "")
        file_path = os.path.join(cluster_dir, f"{safe_name}.md")
        
        # Intra-cluster links (60%)
        intra_candidates = [n for n in all_notes_in_cluster if n != note]
        intra_count = min(random.randint(5, 8), len(intra_candidates))
        intra_links = random.sample(intra_candidates, intra_count)
        
        # Inter-cluster links (40%)
        inter_count = min(random.randint(4, 7), len(other_notes))
        inter_links = random.sample(other_notes, inter_count)
        
        all_links = intra_links + inter_links
        total_links += len(all_links)
        
        links_md = "\n".join([f"- [[{l}]]" for l in all_links])
        
        content = f"""---
type: {cluster}
tags: [knowledge, {cluster.lower()}]
---

# {note}

## Related Concepts
{links_md}
"""
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)

# ============ COUNT FILES ============
print("\n=== Generation Complete ===")
total_files = 0
for cluster in clusters:
    count = len([f for f in os.listdir(os.path.join(base_dir, cluster)) if f.endswith(".md")])
    print(f"{cluster}: {count}")
    total_files += count

print(f"Total files: {total_files}")
print(f"Total links: {total_links}")
print(f"Average links per file: {total_links/total_files:.1f}")
